/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
import Salt.Maynard
import Salt.Maynard.Tuple
import Salt.Maynard.PhiAtom
import Salt.Maynard.KSieve
import Salt.Maynard.GFunction
import Salt.Maynard.Compat
import Salt.Maynard.ChebyshevInterval
import Salt.Maynard.GIntegrals
import Salt.Maynard.Mertens
import Salt.Maynard.Rankin
import Salt.Maynard.CongCount
import Salt.Maynard.Diagonal
import Salt.Maynard.DiagonalS2
import Salt.Maynard.LamBound
import Salt.Maynard.EHConsume
import Salt.Maynard.Ratio
import Salt.Maynard.CrossCollision
import Salt.Maynard.Transfer
import Salt.Maynard.S1Error
import Salt.Maynard.K0
import Salt.Maynard.S2Decomp
import Salt.Maynard.TransferSharp
import Salt.Maynard.CollisionQuant
import Salt.Maynard.LamBoundSharp
import Salt.Maynard.DivisorCount
import Salt.Maynard.S1Bound
import Salt.Maynard.CongSolvable
import Salt.Maynard.S2DiagLam
import Salt.Maynard.S2DiagRestricted
import Salt.Maynard.Lemma53
import Salt.Maynard.S2MainLower
import Salt.Maynard.TensorA1
import Salt.Maynard.Overshoot
import Salt.Maynard.S2Tensor
import Salt.Maynard.HMain
import Salt.Maynard.HOmit
import Salt.Maynard.HMainClose
import Salt.Maynard.S2TensorClosed
import Salt.Maynard.HA11
import Salt.Maynard.OvershootCheb
import Salt.Maynard.S2TensorCheb
import Salt.Maynard.S2Eh
import Salt.Maynard.S2Collision
import Salt.Maynard.VAbs
import Salt.Maynard.EulerTailL
import Salt.Maynard.Lemma53Rel
import Salt.Maynard.S2CompatEH
import Salt.Maynard.S2MainLowerRel
import Salt.Maynard.S2FiberCount
import Salt.Maynard.S2CompatEHFinal
import Salt.Maynard.RatioCore
import Salt.Maynard.Endgame
import Salt.Maynard.Final
import Salt.Maynard.FrontierDischarge
import Salt.Maynard.FrontierFinal
import Salt.Maynard.Lemma53Tight
import Salt.Maynard.Complete
import Salt.Maynard.Level
import Salt.Maynard.LevelConsume
import Salt.Maynard.GehDoor
import Salt.Maynard.GehPiSeam
import Salt.Maynard.GehVaughan
import Salt.Maynard.GehMulti
import Salt.Maynard.GehTypeI
import Salt.Maynard.GehSW
import Salt.Maynard.GehBridge
import Salt.Maynard.GehSmallQ
import Salt.Maynard.GehDecomp
import Salt.Maynard.GehDecomp2
import Salt.Maynard.GehClose
import Salt.Maynard.GehTail
import Salt.Maynard.GehPp
import Salt.Maynard.GehPp2
import Salt.Maynard.GehWindowPnt
import Salt.Maynard.GehSmallQClose
import Salt.Maynard.GehSmallQEst
import Salt.Maynard.TauSpike
import Salt.Maynard.GehAnchor
import Salt.Maynard.PpRootCyc
import Salt.Maynard.PpRootTwo
import Salt.Maynard.PpRootCrt
import Salt.Maynard.ShiuBlocks
import Salt.Maynard.PpFold
import Salt.Maynard.PpRootGeneral
import Salt.Maynard.PpSums
import Salt.Maynard.PpAssembly
import Salt.Maynard.ShiuDecomp
import Salt.Maynard.ShiuRankin
import Salt.Maynard.ShiuSieve
import Salt.Maynard.ShiuGraded
import Salt.Maynard.ShiuClasses
import Salt.Maynard.ShiuTuned
import Salt.Maynard.ShiuClose
import Salt.Maynard.ShiuFinal
import Salt.Maynard.ShiuIV
import Salt.Maynard.ShiuS5
import Salt.Maynard.ShiuS5b
import Salt.Maynard.GehShiuWire
import Salt.Tactic.AuditAxioms

/-! ⟦AUDIT-ROWS 0802⟧ The Maynard capstone, ledger-absent until TROPHY's
census (this file had no audit block at all). -/
#audit_axioms Salt.Maynard.bounded_gaps_from_eh_complete
