/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
import Salt.SW.TBalTall

/-!
# HB 1983, Lemma 7 — node N4b, wave **W2**: the log-weighted composite

Heath-Brown p.209 states an intermediate `(4.11)` on `∑_{u<n≤v} χ(n)Λ(n)/n` and then partial-sums
it into the object his `F`-computation actually consumes,

    ∑_{X<n≤Y} χ(n)Λ(n)/(n log n) = −∫_X^Y v^{β₀−2}(log v)^{−1} dv + O(…),   (4.12)

uniformly in `Y`.  The design freeze's **D3** ruling deletes the standalone `(4.11)`: at the
slowly growing truncation heights this campaign must use (the fixed-height explicit formula has
no power saving — refuter R1), no uniform-error `(4.11)` exists, while the *composite* `(4.12)`
closes with room, because the explicit formula's error is integrated against `dt/(t log t)`
rather than `dt/t`.  So `(4.12)` is proved directly, and this file is where the partial summation
that turns a pointwise `ψ(t,χ)`-bound into `(4.12)` lives.

## The split of labour

* `logChiSum_add_mainTerm_norm_le` — **the composite transfer.**  A pointwise envelope
  `‖ψ(t,χ) + m·t^{β₀}/β₀‖ ≤ t·G t` on `[X,Y]` is turned into

      ‖∑_{X<n≤Y} χ(n)Λ(n)/(n log n) + m·∫_X^Y v^{β₀−2}/log v dv‖
        ≤ G X/log X + G Y/log Y + 2·∫_X^Y G t/(t log t) dt,

  with **no free additive remainder**: the exceptional zero's contribution appears only inside
  the named integral, and everything else is the envelope's own `dt/(t log t)` ledger.  This is
  the multiplicative-mandate shape W3 consumes.  Route: mathlib's Abel identity
  `sum_mul_eq_sub_sub_integral_mul` at the weight `w(t) = (t log t)^{-1}` against the carrier
  `psiChiR`, plus one integration by parts (`intervalIntegral.integral_mul_deriv_eq_deriv_mul`)
  which converts the smooth main term `m·t^{β₀}/β₀` into `m∫ t^{β₀−2}/log t` **exactly** — no
  error is generated by the main term at all.

The envelope `G` itself is the explicit formula's business (the EF socket
`Salt.SW.psi_explicit_sharpM_perZero_unsep` at the growing height `T(u) = (log qu + 2)^6`, the
`β₀` erase-split, the A3-batched erased spend and the Deuring–Heilbronn ceiling); see the report
and `docs/blueprints/flags.md` for the ledger row that fixes the exponent `6`.

Axiom-clean (`propext, Classical.choice, Quot.sound`); no `native_decide`.
-/

open Complex DirichletCharacter ArithmeticFunction Filter Set MeasureTheory
open Salt.SW
open scoped Topology

namespace Salt.HB

/-! ## 1. The Abel weight `w(t) = 1/(t log t)` and its derivative -/

/-- The partial-summation weight of HB's `(4.12)`: `w(t) = (t·log t)^{-1}`. -/
noncomputable def wLog (t : ℝ) : ℝ := (t * Real.log t)⁻¹

/-- The derivative of `wLog`: `w'(t) = −(log t + 1)/(t log t)^2`. -/
noncomputable def wLog' (t : ℝ) : ℝ := -(Real.log t + 1) / (t * Real.log t) ^ 2

lemma hasDerivAt_wLog {t : ℝ} (ht : 1 < t) : HasDerivAt wLog (wLog' t) t := by
  have ht0 : (0 : ℝ) < t := by linarith
  have hlog : 0 < Real.log t := Real.log_pos ht
  have hne : t * Real.log t ≠ 0 := by positivity
  have h1 : HasDerivAt (fun s : ℝ => s * Real.log s) (Real.log t + 1) t := by
    have h := (hasDerivAt_id t).mul (Real.hasDerivAt_log (ne_of_gt ht0))
    simp only [id_eq, one_mul] at h
    rwa [mul_inv_cancel₀ (ne_of_gt ht0)] at h
  exact h1.inv hne

/-- The complexified weight, the shape mathlib's Abel identity consumes. -/
lemma hasDerivAt_wLogC {t : ℝ} (ht : 1 < t) :
    HasDerivAt (fun s : ℝ => ((wLog s : ℝ) : ℂ)) ((wLog' t : ℝ) : ℂ) t :=
  (hasDerivAt_wLog ht).ofReal_comp

lemma deriv_wLogC {t : ℝ} (ht : 1 < t) :
    deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t = ((wLog' t : ℝ) : ℂ) :=
  (hasDerivAt_wLogC ht).deriv

lemma wLog_nonneg {t : ℝ} (ht : 1 ≤ t) : 0 ≤ wLog t := by
  have : 0 ≤ Real.log t := Real.log_nonneg ht
  rw [wLog]; positivity

lemma wLog'_nonpos {t : ℝ} (ht : 1 ≤ t) : wLog' t ≤ 0 := by
  have h : 0 ≤ Real.log t := Real.log_nonneg ht
  rw [wLog']
  apply div_nonpos_of_nonpos_of_nonneg (by linarith) (sq_nonneg _)

lemma continuousOn_wLog {s : Set ℝ} (hs : ∀ t ∈ s, 1 < t) : ContinuousOn wLog s := by
  refine ContinuousOn.inv₀ (continuousOn_id.mul (Real.continuousOn_log.mono ?_)) ?_
  · intro t ht
    exact ne_of_gt (lt_trans one_pos (hs t ht))
  · intro t ht
    have h1 := hs t ht
    have : 0 < Real.log t := Real.log_pos h1
    positivity

lemma continuousOn_wLog' {s : Set ℝ} (hs : ∀ t ∈ s, 1 < t) : ContinuousOn wLog' s := by
  have hc : ContinuousOn (fun t : ℝ => t * Real.log t) s :=
    continuousOn_id.mul (Real.continuousOn_log.mono
      (fun t ht => ne_of_gt (lt_trans one_pos (hs t ht))))
  have hnum : ContinuousOn (fun t : ℝ => -(Real.log t + 1)) s :=
    (((Real.continuousOn_log.mono
      (fun t ht => ne_of_gt (lt_trans one_pos (hs t ht)))).add continuousOn_const).neg)
  refine ContinuousOn.div hnum (hc.pow 2) ?_
  intro t ht
  have h1 := hs t ht
  have : 0 < Real.log t := Real.log_pos h1
  positivity

/-! ## 2. The carrier's `Icc 0` packaging -/

/-- `∑_{k ≤ t} Λ(k)χ(k) = ψ(t,χ)`: the `k = 0` term of mathlib's Abel range vanishes. -/
lemma sum_Icc_zero_eq_psiChiR {q : ℕ} (χ : DirichletCharacter ℂ q) (t : ℝ) :
    ∑ k ∈ Finset.Icc 0 ⌊t⌋₊, ((vonMangoldt k : ℂ) * χ (k : ZMod q)) = psiChiR t χ := by
  rw [psiChiR_def]
  refine (Finset.sum_subset (fun x hx => ?_) (fun x hx hx' => ?_)).symm
  · rw [Finset.mem_Icc] at hx ⊢; omega
  · rw [Finset.mem_Icc] at hx
    rw [Finset.mem_Icc] at hx'
    have hx0 : x = 0 := by omega
    subst hx0
    simp

/-! ## 3. The composite transfer (D3's deliverable) -/

/-- **The explicit formula's defect at the exceptional zero**: `ψ(t,χ) + m·t^{β₀}/β₀`.  The
`(1.11)` zero's residue is the ONLY zero term subtracted here — everything else the explicit
formula produces is charged to the envelope `G`. -/
noncomputable def psiDefect {q : ℕ} (χ : DirichletCharacter ℂ q) (β₀ : ℝ) (m : ℕ) (t : ℝ) : ℂ :=
  psiChiR t χ + (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ)

/-- The log-weighted character sum `∑_{X < n ≤ Y} χ(n)Λ(n)/(n log n)`. -/
noncomputable def logChiSum {q : ℕ} (χ : DirichletCharacter ℂ q) (X Y : ℝ) : ℂ :=
  ∑ n ∈ Finset.Ioc ⌊X⌋₊ ⌊Y⌋₊, ((wLog n : ℝ) : ℂ) * ((vonMangoldt n : ℂ) * χ (n : ZMod q))

/-- **The Abel identity at the weight `1/(t log t)`.**  Mathlib's
`sum_mul_eq_sub_sub_integral_mul` fired at `c n = Λ(n)χ(n)`, whose partial sums are exactly the
sharp carrier `psiChiR`. -/
lemma abel_logChiSum {q : ℕ} (χ : DirichletCharacter ℂ q) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y) :
    logChiSum χ X Y
      = ((wLog Y : ℝ) : ℂ) * psiChiR Y χ - ((wLog X : ℝ) : ℂ) * psiChiR X χ
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hmem : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hderiv : ∀ t ∈ Set.Icc X Y,
      deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t = ((wLog' t : ℝ) : ℂ) :=
    fun t ht => deriv_wLogC (hmem t ht)
  have hcont : ContinuousOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    Complex.continuous_ofReal.comp_continuousOn (continuousOn_wLog' hmem)
  have hIntFd : IntegrableOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    hcont.integrableOn_compact isCompact_Icc
  have hf_int : IntegrableOn (deriv fun s : ℝ => ((wLog s : ℝ) : ℂ)) (Set.Icc X Y) :=
    hIntFd.congr_fun (fun t ht => (hderiv t ht).symm) measurableSet_Icc
  have hf_diff : ∀ t ∈ Set.Icc X Y, DifferentiableAt ℝ (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t :=
    fun t ht => (hasDerivAt_wLogC (hmem t ht)).differentiableAt
  have habel := sum_mul_eq_sub_sub_integral_mul
    (fun n : ℕ => ((vonMangoldt n : ℂ) * χ (n : ZMod q)))
    (f := fun s : ℝ => ((wLog s : ℝ) : ℂ)) (by linarith : (0:ℝ) ≤ X) hXY hf_diff hf_int
  rw [sum_Icc_zero_eq_psiChiR, sum_Icc_zero_eq_psiChiR] at habel
  have hint : (∫ t in Set.Ioc X Y, deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t
        * ∑ k ∈ Finset.Icc 0 ⌊t⌋₊, ((vonMangoldt k : ℂ) * χ (k : ZMod q)))
      = ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ := by
    rw [intervalIntegral.integral_of_le hXY]
    refine setIntegral_congr_fun measurableSet_Ioc (fun t ht => ?_)
    rw [hderiv t ⟨le_of_lt ht.1, ht.2⟩, sum_Icc_zero_eq_psiChiR]
  rw [logChiSum, habel, hint]

/-- **The main term crosses the partial summation exactly.**  Integration by parts at
`u = 1/(t log t)`, `v = m·t^{β₀}/β₀`: the boundary terms and the `w'`-integral reassemble into
`m·∫_X^Y v^{β₀−2}/log v dv` with **no** error term. -/
lemma mainTerm_ibp {β₀ : ℝ} (hβ₀0 : 0 < β₀) (m : ℕ) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y) :
    (m : ℝ) * (∫ t in X..Y, t ^ (β₀ - 2) / Real.log t)
      = wLog Y * ((m : ℝ) * Y ^ β₀ / β₀) - wLog X * ((m : ℝ) * X ^ β₀ / β₀)
        - ∫ t in X..Y, wLog' t * ((m : ℝ) * t ^ β₀ / β₀) := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hβne : β₀ ≠ 0 := ne_of_gt hβ₀0
  have huIcc : Set.uIcc X Y = Set.Icc X Y := Set.uIcc_of_le hXY
  have hmemIcc : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hmem : ∀ t ∈ Set.uIcc X Y, (1 : ℝ) < t := by rw [huIcc]; exact hmemIcc
  have hu : ∀ t ∈ Set.uIcc X Y, HasDerivAt wLog (wLog' t) t :=
    fun t ht => hasDerivAt_wLog (hmem t ht)
  have hv : ∀ t ∈ Set.uIcc X Y,
      HasDerivAt (fun s : ℝ => (m : ℝ) * s ^ β₀ / β₀) ((m : ℝ) * t ^ (β₀ - 1)) t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmem t ht)
    have h1 : HasDerivAt (fun s : ℝ => s ^ β₀) (β₀ * t ^ (β₀ - 1)) t :=
      Real.hasDerivAt_rpow_const (Or.inl (ne_of_gt ht0))
    have h2 := (h1.const_mul (m : ℝ)).div_const β₀
    have heq : (m : ℝ) * (β₀ * t ^ (β₀ - 1)) / β₀ = (m : ℝ) * t ^ (β₀ - 1) := by
      field_simp
    rw [heq] at h2
    exact h2
  have hu' : IntervalIntegrable wLog' volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    exact (continuousOn_wLog' hmemIcc).integrableOn_compact isCompact_Icc
  have hv' : IntervalIntegrable (fun t : ℝ => (m : ℝ) * t ^ (β₀ - 1)) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    exact (continuousOn_const.mul (ContinuousOn.rpow_const continuousOn_id
      (fun t ht => Or.inl (ne_of_gt (lt_trans one_pos (hmemIcc t ht)))))).integrableOn_compact
      isCompact_Icc
  have hibp := intervalIntegral.integral_mul_deriv_eq_deriv_mul hu hv hu' hv'
  rw [← hibp, ← intervalIntegral.integral_const_mul]
  refine intervalIntegral.integral_congr (fun t ht => ?_)
  have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmem t ht)
  have hlt : 0 < Real.log t := Real.log_pos (hmem t ht)
  have hrp : t ^ (β₀ - 2) = t ^ (β₀ - 1) / t := by
    rw [show β₀ - 2 = (β₀ - 1) - 1 from by ring, Real.rpow_sub ht0, Real.rpow_one]
  rw [wLog, hrp]
  field_simp

/-- **THE COMPOSITE TRANSFER (N4b W2, design D3).**  A pointwise explicit-formula envelope on
`[X,Y]`,

    ‖ψ(t,χ) + m·t^{β₀}/β₀‖ ≤ t·G t,

partial-sums into HB's `(4.12)`:

    ‖∑_{X<n≤Y} χ(n)Λ(n)/(n log n) + m·∫_X^Y v^{β₀−2}/log v dv‖
      ≤ G X/log X + G Y/log Y + 2·∫_X^Y G t/(t log t) dt.

The exceptional zero's main term crosses the partial summation **exactly** — the integration by
parts `∫ w·(m t^{β₀−1}) = w(Y)M(Y) − w(X)M(X) − ∫ w'·M` is an identity, so no error at all is
charged to it; every term on the right is the envelope's own `dt/(t log t)` ledger.  This is the
`(4.12)`-form's multiplicative mandate: no free additive remainder reaches the consumer.

`m` rides explicitly (no simplicity hypothesis anywhere); `β₀` is real with `0 < β₀ < 1`. -/
theorem logChiSum_add_mainTerm_norm_le {q : ℕ} (χ : DirichletCharacter ℂ q)
    {β₀ : ℝ} (hβ₀0 : 0 < β₀) (m : ℕ) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y)
    {G : ℝ → ℝ} (hGc : ContinuousOn G (Set.Icc X Y)) (hG0 : ∀ t ∈ Set.Icc X Y, 0 ≤ G t)
    (hEF : ∀ t ∈ Set.Icc X Y, ‖psiDefect χ β₀ m t‖ ≤ t * G t) :
    ‖logChiSum χ X Y + (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)‖
      ≤ G X / Real.log X + G Y / Real.log Y
        + 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hY3 : (3 : ℝ) ≤ Y := le_trans hX hXY
  have huIcc : Set.uIcc X Y = Set.Icc X Y := Set.uIcc_of_le hXY
  have hmemIcc : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hXmem : X ∈ Set.Icc X Y := ⟨le_rfl, hXY⟩
  have hYmem : Y ∈ Set.Icc X Y := ⟨hXY, le_rfl⟩
  have hlog1 : ∀ t ∈ Set.Icc X Y, (1 : ℝ) ≤ Real.log t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
    have hte : Real.exp 1 ≤ t :=
      le_trans (le_of_lt (lt_trans Real.exp_one_lt_d9 (by norm_num))) (le_trans hX ht.1)
    exact (Real.le_log_iff_exp_le ht0).mpr hte
  -- the ℂ form of the exact main-term identity
  have hcast : (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ))
      = ((∫ t in X..Y, wLog' t * ((m : ℝ) * t ^ β₀ / β₀) : ℝ) : ℂ) := by
    rw [← intervalIntegral.integral_ofReal]
    exact intervalIntegral.integral_congr (fun t _ => by push_cast; ring)
  have hmain : (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)
      = ((wLog Y : ℝ) : ℂ) * (((m : ℝ) * Y ^ β₀ / β₀ : ℝ) : ℂ)
        - ((wLog X : ℝ) : ℂ) * (((m : ℝ) * X ^ β₀ / β₀ : ℝ) : ℂ)
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ) := by
    rw [hcast, show ((m : ℂ)) = (((m : ℝ)) : ℂ) from by push_cast; ring,
      ← Complex.ofReal_mul, mainTerm_ibp hβ₀0 m hX hXY]
    push_cast
    ring
  -- the three integrability facts
  have hcontFd : ContinuousOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    Complex.continuous_ofReal.comp_continuousOn (continuousOn_wLog' hmemIcc)
  have hIΨ : IntervalIntegrable (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * psiChiR t χ) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    have h0 := integrableOn_mul_sum_Icc (fun n : ℕ => ((vonMangoldt n : ℂ) * χ (n : ZMod q)))
      (m := 0) (b := Y) (by linarith : (0:ℝ) ≤ X)
      (hcontFd.integrableOn_compact isCompact_Icc)
    exact h0.congr_fun (fun t _ => by simp [sum_Icc_zero_eq_psiChiR]) measurableSet_Icc
  have hIM : IntervalIntegrable
      (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ)) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    refine ContinuousOn.integrableOn_compact isCompact_Icc (hcontFd.mul ?_)
    refine Complex.continuous_ofReal.comp_continuousOn ?_
    exact ((continuousOn_const.mul (ContinuousOn.rpow_const continuousOn_id
      (fun t ht => Or.inl (ne_of_gt (lt_trans one_pos (hmemIcc t ht)))))).div_const β₀)
  have hID : IntervalIntegrable (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t)
      volume X Y := by
    refine (hIΨ.add hIM).congr (fun t _ => ?_)
    rw [psiDefect]; ring
  -- the exact assembly
  have hsplit : (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ)
      = (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t)
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ) := by
    rw [← intervalIntegral.integral_sub hID hIM]
    exact intervalIntegral.integral_congr (fun t _ => by rw [psiDefect]; ring)
  have hkey : logChiSum χ X Y + (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)
      = ((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t := by
    rw [abel_logChiSum χ hX hXY, hmain, hsplit]
    simp only [psiDefect]
    ring
  rw [hkey]
  -- the three norm rows
  have hbdry : ∀ t ∈ Set.Icc X Y, ‖((wLog t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ G t / Real.log t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
    have hlt : (1 : ℝ) ≤ Real.log t := hlog1 t ht
    have hltpos : (0 : ℝ) < Real.log t := by linarith
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (wLog_nonneg (le_of_lt
      (hmemIcc t ht)))]
    calc wLog t * ‖psiDefect χ β₀ m t‖
        ≤ wLog t * (t * G t) :=
          mul_le_mul_of_nonneg_left (hEF t ht) (wLog_nonneg (le_of_lt (hmemIcc t ht)))
      _ = G t / Real.log t := by rw [wLog]; field_simp
  have hint : ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
    have hIG : IntervalIntegrable (fun t : ℝ => 2 * (G t / (t * Real.log t))) volume X Y := by
      rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
      refine ContinuousOn.integrableOn_compact isCompact_Icc (continuousOn_const.mul ?_)
      refine hGc.div (continuousOn_id.mul (Real.continuousOn_log.mono
        (fun t ht => ne_of_gt (lt_trans one_pos (hmemIcc t ht))))) ?_
      intro t ht
      have h1 := hmemIcc t ht
      have : 0 < Real.log t := Real.log_pos h1
      positivity
    calc ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
        ≤ ∫ t in X..Y, ‖((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ :=
          intervalIntegral.norm_integral_le_integral_norm hXY
      _ ≤ ∫ t in X..Y, 2 * (G t / (t * Real.log t)) := by
          refine intervalIntegral.integral_mono_on hXY hID.norm hIG (fun t ht => ?_)
          have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
          have hlt : (1 : ℝ) ≤ Real.log t := hlog1 t ht
          have hltpos : (0 : ℝ) < Real.log t := by linarith
          have hGt : 0 ≤ G t := hG0 t ht
          rw [norm_mul, Complex.norm_real, Real.norm_eq_abs,
            abs_of_nonpos (wLog'_nonpos (le_of_lt (hmemIcc t ht)))]
          have hw : -wLog' t = (Real.log t + 1) / (t * Real.log t) ^ 2 := by
            rw [wLog']; ring
          rw [hw]
          calc (Real.log t + 1) / (t * Real.log t) ^ 2 * ‖psiDefect χ β₀ m t‖
              ≤ (Real.log t + 1) / (t * Real.log t) ^ 2 * (t * G t) :=
                mul_le_mul_of_nonneg_left (hEF t ht) (by positivity)
            _ ≤ 2 * (G t / (t * Real.log t)) := by
                rw [div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
                have hsq : (t * Real.log t) ^ 2 = t * Real.log t * (t * Real.log t) := by ring
                rw [hsq]
                have hkey2 : (Real.log t + 1) * (t * G t) ≤ 2 * Real.log t * (t * G t) := by
                  nlinarith [mul_nonneg (le_of_lt ht0) hGt]
                calc (Real.log t + 1) * (t * G t)
                    ≤ 2 * Real.log t * (t * G t) := hkey2
                  _ = 2 * (G t / (t * Real.log t)) * (t * Real.log t * (t * Real.log t)) := by
                      field_simp
      _ = 2 * ∫ t in X..Y, G t / (t * Real.log t) := intervalIntegral.integral_const_mul _ _
  calc ‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ ‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X‖
          + ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ := norm_sub_le _ _
    _ ≤ (‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y‖
          + ‖((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X‖)
          + ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ :=
        add_le_add (norm_sub_le _ _) le_rfl
    _ ≤ (G Y / Real.log Y + G X / Real.log X) + 2 * ∫ t in X..Y, G t / (t * Real.log t) :=
        add_le_add (add_le_add (hbdry Y hYmem) (hbdry X hXmem)) hint
    _ = G X / Real.log X + G Y / Real.log Y + 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
        ring

/-! ## 4. The explicit-formula side — the socket to `psiDefect` bridge -/

/-- **THE EF BRIDGE (N4b W2, design D1/D2/D4).**  The W0.5 socket
`psi_explicit_sharpM_perZero_unsep` (no well-spacing hypothesis: it pigeonholes internally)
composed with

* the `β₀` erase-split `efZeroSumM_erase_split` — which is **forced**, not merely convenient:
  the packaged `boxZeros_re_le_of_repulsion` cannot be used on a box containing `β₀` (its `hreal`
  demands every real zero of the box obey the repulsion ceiling, and `β₀` by construction does
  not);
* the A3-batched erased spend `efZeroSumM_norm_le_harmonic` × `efMultHarmonic_box_le` — the
  `log(qT)·log T` grade, never the `T·log(qT)` count;
* the same erase-split applied to the de-smoothing sum, so that `β₀`'s de-smoothing term keeps
  its own `u^{β₀−1}` and only the REST is charged the ceiling `bceil` (collapsing the whole sum to
  `efMultTotal·h` would be fatal — that term alone is `≈ 274·√T·log(qT)` relative).

The single carried ceiling binder is

    hceil : every zero `ρ ≠ β₀` of the strip `9/10 ≤ Re ρ ≤ 1`, `|Im ρ| ≤ T₀+1`, has `Re ρ ≤ bceil`,

which is exactly what the Range-A Deuring–Heilbronn ceiling (`dh_repulsion_tall` fed through the
`erase`-form of `boxZeros_re_le_of_repulsion`, under `hord`/`hreal′`/`hN+`) and the Range-B
`zero_free_region_all` ceiling supply; `hσbβ₀` is the statement that the `(1.11)` zero sits above
the contour window, and `hβ₀0` that it is a zero at all.  Nothing is silent: `m := zeroMult χ β₀`
rides explicitly, and the surviving `efShiftError` is the landed contour budget verbatim (its
explicit evaluation is the ledger row recorded in `docs/blueprints/flags.md`). -/
theorem psiDefect_norm_le_of_ef {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hq : 2 ≤ q) {β₀ bceil u h σa σb T₀ : ℝ}
    (hu : 3 ≤ u) (hh : 0 < h) (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hT₀ : 2 ≤ T₀) (hβ₀1 : β₀ ≤ 1) (hσbβ₀ : σb ≤ β₀)
    (hβ₀zero : LFunction χ (β₀ : ℂ) = 0)
    (hceil : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
      |ρ.im| ≤ T₀ + 1 → ρ.re ≤ bceil) :
    ∃ σ₀ T w : ℝ,
      (σa ≤ σ₀ ∧ σ₀ ≤ σb) ∧ (T₀ ≤ T ∧ T ≤ T₀ + 1) ∧ 0 < w ∧
      (σb - σa) / (4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1)) ≤ w ∧
      ‖psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u‖
        ≤ (h + 1) * Real.log (u + h)
          + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
          + ((zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
              + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))))
          + u ^ bceil * (137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1))) := by
  classical
  have hχ1 : χ ≠ 1 := ne_one_of_isPrimitive χ hχ hq
  have hu1 : (1 : ℝ) ≤ u := by linarith
  have hu0 : (0 : ℝ) < u := by linarith
  obtain ⟨σ₀, T, w, hσ, hT, hw, hwlb, hσ₀w, hσ₀1, hsock⟩ :=
    psi_explicit_sharpM_perZero_unsep χ hχ hq hu hh hσa hσab hσb hT₀
  refine ⟨σ₀, T, w, hσ, hT, hw, hwlb, ?_⟩
  have hT0 : (0 : ℝ) ≤ T := by linarith [hT.1]
  -- `β₀` lies in the contour box
  have hβZ : (β₀ : ℂ) ∈ boxZeros χ (σ₀ - w) 1 T := by
    rw [mem_boxZeros hχ1]
    refine ⟨hβ₀zero, ?_, ?_, ?_⟩
    · simp only [Complex.ofReal_re]; linarith [hσ.2]
    · simpa using hβ₀1
    · simp only [Complex.ofReal_im, abs_zero]; linarith [hT.1]
  -- the ceiling, on the ERASED box (the `hreal`-at-`β₀` repair)
  have hbar : ∀ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ), ρ.re ≤ bceil := by
    intro ρ hρ
    have hmem := (mem_boxZeros hχ1).mp (Finset.mem_of_mem_erase hρ)
    exact hceil ρ hmem.1 (Finset.ne_of_mem_erase hρ) (by linarith [hmem.2.1])
      hmem.2.2.1 (le_trans hmem.2.2.2 hT.2)
  -- the box's own strip data, for the A3 batching and the count
  have hZ0 : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, LFunction χ ρ = 0 :=
    fun ρ hρ => ((mem_boxZeros hχ1).mp hρ).1
  have hZre : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, 1 / 2 ≤ ρ.re ∧ ρ.re ≤ 1 := by
    intro ρ hρ
    have hmem := (mem_boxZeros hχ1).mp hρ
    exact ⟨by linarith [hmem.2.1], hmem.2.2.1⟩
  have hZim : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, |ρ.im| ≤ T :=
    fun ρ hρ => ((mem_boxZeros hχ1).mp hρ).2.2.2
  -- the exceptional residue is exactly `psiDefect`'s main term
  have hres : (((zeroMult χ (β₀ : ℂ) : ℝ) * u ^ β₀ / β₀ : ℝ) : ℂ)
      = (zeroMult χ (β₀ : ℂ) : ℂ) * (((u : ℝ) : ℂ) ^ (β₀ : ℂ) / (β₀ : ℂ)) := by
    push_cast [Complex.ofReal_cpow (le_of_lt hu0)]
    ring
  have hkey : psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u
      = (psiChiR u χ + efZeroSumM χ (boxZeros χ (σ₀ - w) 1 T) u)
        - efZeroSumM χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) u := by
    rw [efZeroSumM_erase_split χ hβZ u, psiDefect, hres]
    ring
  -- the A3-batched erased spend
  have hspend : ‖efZeroSumM χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) u‖
      ≤ u ^ bceil * (137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1))) := by
    refine le_trans (efZeroSumM_norm_le_harmonic χ hu1 hbar) ?_
    refine mul_le_mul_of_nonneg_left ?_ (Real.rpow_nonneg (by linarith) bceil)
    refine le_trans (Finset.sum_le_sum_of_subset_of_nonneg (Finset.erase_subset _ _)
      (fun i _ _ => div_nonneg (by positivity) (norm_nonneg i))) ?_
    exact efMultHarmonic_box_le χ hχ hq hT0 hZ0 hZre hZim
  -- the de-smoothing sum, `β₀` kept apart from the ceiling
  have hcount : efMultTotal χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ))
      ≤ 137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3)) := by
    refine le_trans (Finset.sum_le_sum_of_subset_of_nonneg (Finset.erase_subset _ _)
      (fun i _ _ => by positivity)) ?_
    exact zeroCountM_le χ hχ hq (by linarith : (1:ℝ)/2 ≤ σ₀ - w) hT0
  have hdesm : ∑ ρ ∈ boxZeros χ (σ₀ - w) 1 T, (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
      ≤ (zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
        + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) := by
    rw [← Finset.add_sum_erase _ (fun ρ => (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))) hβZ]
    simp only [Complex.ofReal_re]
    refine add_le_add le_rfl ?_
    calc ∑ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ),
          (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
        ≤ ∑ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ),
            (zeroMult χ ρ : ℝ) * (h * u ^ (bceil - 1)) := by
          refine Finset.sum_le_sum (fun ρ hρ => ?_)
          refine mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left ?_ (le_of_lt hh))
            (by positivity)
          exact Real.rpow_le_rpow_of_exponent_le hu1 (by linarith [hbar ρ hρ])
      _ = efMultTotal χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) * (h * u ^ (bceil - 1)) := by
          rw [efMultTotal, Finset.sum_mul]
      _ ≤ (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) * (h * u ^ (bceil - 1)) := by
          refine mul_le_mul_of_nonneg_right hcount ?_
          have : (0:ℝ) < u ^ (bceil - 1) := Real.rpow_pos_of_pos hu0 _
          positivity
      _ = h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) := by ring
  -- assembly
  rw [hkey]
  refine le_trans (norm_sub_le _ _) ?_
  have := le_trans hsock (by linarith [hdesm] :
    (h + 1) * Real.log (u + h)
      + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
      + ∑ ρ ∈ boxZeros χ (σ₀ - w) 1 T, (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
    ≤ (h + 1) * Real.log (u + h)
      + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
      + ((zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
          + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3)))))
  linarith [this, hspend]

end Salt.HB
