/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
import Salt.SW.TBalTall

/-!
# HB 1983, Lemma 7 — node N4b, wave **W2**: the log-weighted composite

Heath-Brown p.209 states an intermediate `(4.11)` on `∑_{u<n≤v} χ(n)Λ(n)/n` and then partial-sums
it into the object his `F`-computation actually consumes,

    ∑_{X<n≤Y} χ(n)Λ(n)/(n log n) = −∫_X^Y v^{β₀−2}(log v)^{−1} dv + O(…),   (4.12)

uniformly in `Y`.  The design freeze's **D3** ruling deletes the standalone `(4.11)`: at the
slowly growing truncation heights this campaign must use (the fixed-height explicit formula has
no power saving — refuter R1), no uniform-error `(4.11)` exists, while the *composite* `(4.12)`
closes with room, because the explicit formula's error is integrated against `dt/(t log t)`
rather than `dt/t`.  So `(4.12)` is proved directly, and this file is where the partial summation
that turns a pointwise `ψ(t,χ)`-bound into `(4.12)` lives.

## The split of labour

* `logChiSum_add_mainTerm_norm_le` — **the composite transfer.**  A pointwise envelope
  `‖ψ(t,χ) + m·t^{β₀}/β₀‖ ≤ t·G t` on `[X,Y]` is turned into

      ‖∑_{X<n≤Y} χ(n)Λ(n)/(n log n) + m·∫_X^Y v^{β₀−2}/log v dv‖
        ≤ G X/log X + G Y/log Y + 2·∫_X^Y G t/(t log t) dt,

  with **no free additive remainder**: the exceptional zero's contribution appears only inside
  the named integral, and everything else is the envelope's own `dt/(t log t)` ledger.  This is
  the multiplicative-mandate shape W3 consumes.  Route: mathlib's Abel identity
  `sum_mul_eq_sub_sub_integral_mul` at the weight `w(t) = (t log t)^{-1}` against the carrier
  `psiChiR`, plus one integration by parts (`intervalIntegral.integral_mul_deriv_eq_deriv_mul`)
  which converts the smooth main term `m·t^{β₀}/β₀` into `m∫ t^{β₀−2}/log t` **exactly** — no
  error is generated by the main term at all.

The envelope `G` itself is the explicit formula's business (the EF socket
`Salt.SW.psi_explicit_sharpM_perZero_unsep` at the growing height `T(u) = (log qu + 2)^6`, the
`β₀` erase-split, the A3-batched erased spend and the Deuring–Heilbronn ceiling); see the report
and `docs/blueprints/flags.md` for the ledger row that fixes the exponent `6`.

Axiom-clean (`propext, Classical.choice, Quot.sound`); no `native_decide`.
-/

open Complex DirichletCharacter ArithmeticFunction Filter Set MeasureTheory
open Salt.SW
open scoped Topology

namespace Salt.HB

/-! ## 1. The Abel weight `w(t) = 1/(t log t)` and its derivative -/

/-- The partial-summation weight of HB's `(4.12)`: `w(t) = (t·log t)^{-1}`. -/
noncomputable def wLog (t : ℝ) : ℝ := (t * Real.log t)⁻¹

/-- The derivative of `wLog`: `w'(t) = −(log t + 1)/(t log t)^2`. -/
noncomputable def wLog' (t : ℝ) : ℝ := -(Real.log t + 1) / (t * Real.log t) ^ 2

lemma hasDerivAt_wLog {t : ℝ} (ht : 1 < t) : HasDerivAt wLog (wLog' t) t := by
  have ht0 : (0 : ℝ) < t := by linarith
  have hlog : 0 < Real.log t := Real.log_pos ht
  have hne : t * Real.log t ≠ 0 := by positivity
  have h1 : HasDerivAt (fun s : ℝ => s * Real.log s) (Real.log t + 1) t := by
    have h := (hasDerivAt_id t).mul (Real.hasDerivAt_log (ne_of_gt ht0))
    simp only [id_eq, one_mul] at h
    rwa [mul_inv_cancel₀ (ne_of_gt ht0)] at h
  exact h1.inv hne

/-- The complexified weight, the shape mathlib's Abel identity consumes. -/
lemma hasDerivAt_wLogC {t : ℝ} (ht : 1 < t) :
    HasDerivAt (fun s : ℝ => ((wLog s : ℝ) : ℂ)) ((wLog' t : ℝ) : ℂ) t :=
  (hasDerivAt_wLog ht).ofReal_comp

lemma deriv_wLogC {t : ℝ} (ht : 1 < t) :
    deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t = ((wLog' t : ℝ) : ℂ) :=
  (hasDerivAt_wLogC ht).deriv

lemma wLog_nonneg {t : ℝ} (ht : 1 ≤ t) : 0 ≤ wLog t := by
  have : 0 ≤ Real.log t := Real.log_nonneg ht
  rw [wLog]; positivity

lemma wLog'_nonpos {t : ℝ} (ht : 1 ≤ t) : wLog' t ≤ 0 := by
  have h : 0 ≤ Real.log t := Real.log_nonneg ht
  rw [wLog']
  apply div_nonpos_of_nonpos_of_nonneg (by linarith) (sq_nonneg _)

lemma continuousOn_wLog {s : Set ℝ} (hs : ∀ t ∈ s, 1 < t) : ContinuousOn wLog s := by
  refine ContinuousOn.inv₀ (continuousOn_id.mul (Real.continuousOn_log.mono ?_)) ?_
  · intro t ht
    exact ne_of_gt (lt_trans one_pos (hs t ht))
  · intro t ht
    have h1 := hs t ht
    have : 0 < Real.log t := Real.log_pos h1
    positivity

lemma continuousOn_wLog' {s : Set ℝ} (hs : ∀ t ∈ s, 1 < t) : ContinuousOn wLog' s := by
  have hc : ContinuousOn (fun t : ℝ => t * Real.log t) s :=
    continuousOn_id.mul (Real.continuousOn_log.mono
      (fun t ht => ne_of_gt (lt_trans one_pos (hs t ht))))
  have hnum : ContinuousOn (fun t : ℝ => -(Real.log t + 1)) s :=
    (((Real.continuousOn_log.mono
      (fun t ht => ne_of_gt (lt_trans one_pos (hs t ht)))).add continuousOn_const).neg)
  refine ContinuousOn.div hnum (hc.pow 2) ?_
  intro t ht
  have h1 := hs t ht
  have : 0 < Real.log t := Real.log_pos h1
  positivity

/-! ## 2. The carrier's `Icc 0` packaging -/

/-- `∑_{k ≤ t} Λ(k)χ(k) = ψ(t,χ)`: the `k = 0` term of mathlib's Abel range vanishes. -/
lemma sum_Icc_zero_eq_psiChiR {q : ℕ} (χ : DirichletCharacter ℂ q) (t : ℝ) :
    ∑ k ∈ Finset.Icc 0 ⌊t⌋₊, ((vonMangoldt k : ℂ) * χ (k : ZMod q)) = psiChiR t χ := by
  rw [psiChiR_def]
  refine (Finset.sum_subset (fun x hx => ?_) (fun x hx hx' => ?_)).symm
  · rw [Finset.mem_Icc] at hx ⊢; omega
  · rw [Finset.mem_Icc] at hx
    rw [Finset.mem_Icc] at hx'
    have hx0 : x = 0 := by omega
    subst hx0
    simp

/-! ## 3. The composite transfer (D3's deliverable) -/

/-- **The explicit formula's defect at the exceptional zero**: `ψ(t,χ) + m·t^{β₀}/β₀`.  The
`(1.11)` zero's residue is the ONLY zero term subtracted here — everything else the explicit
formula produces is charged to the envelope `G`. -/
noncomputable def psiDefect {q : ℕ} (χ : DirichletCharacter ℂ q) (β₀ : ℝ) (m : ℕ) (t : ℝ) : ℂ :=
  psiChiR t χ + (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ)

/-- The log-weighted character sum `∑_{X < n ≤ Y} χ(n)Λ(n)/(n log n)`. -/
noncomputable def logChiSum {q : ℕ} (χ : DirichletCharacter ℂ q) (X Y : ℝ) : ℂ :=
  ∑ n ∈ Finset.Ioc ⌊X⌋₊ ⌊Y⌋₊, ((wLog n : ℝ) : ℂ) * ((vonMangoldt n : ℂ) * χ (n : ZMod q))

/-- **The Abel identity at the weight `1/(t log t)`.**  Mathlib's
`sum_mul_eq_sub_sub_integral_mul` fired at `c n = Λ(n)χ(n)`, whose partial sums are exactly the
sharp carrier `psiChiR`. -/
lemma abel_logChiSum {q : ℕ} (χ : DirichletCharacter ℂ q) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y) :
    logChiSum χ X Y
      = ((wLog Y : ℝ) : ℂ) * psiChiR Y χ - ((wLog X : ℝ) : ℂ) * psiChiR X χ
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hmem : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hderiv : ∀ t ∈ Set.Icc X Y,
      deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t = ((wLog' t : ℝ) : ℂ) :=
    fun t ht => deriv_wLogC (hmem t ht)
  have hcont : ContinuousOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    Complex.continuous_ofReal.comp_continuousOn (continuousOn_wLog' hmem)
  have hIntFd : IntegrableOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    hcont.integrableOn_compact isCompact_Icc
  have hf_int : IntegrableOn (deriv fun s : ℝ => ((wLog s : ℝ) : ℂ)) (Set.Icc X Y) :=
    hIntFd.congr_fun (fun t ht => (hderiv t ht).symm) measurableSet_Icc
  have hf_diff : ∀ t ∈ Set.Icc X Y, DifferentiableAt ℝ (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t :=
    fun t ht => (hasDerivAt_wLogC (hmem t ht)).differentiableAt
  have habel := sum_mul_eq_sub_sub_integral_mul
    (fun n : ℕ => ((vonMangoldt n : ℂ) * χ (n : ZMod q)))
    (f := fun s : ℝ => ((wLog s : ℝ) : ℂ)) (by linarith : (0:ℝ) ≤ X) hXY hf_diff hf_int
  rw [sum_Icc_zero_eq_psiChiR, sum_Icc_zero_eq_psiChiR] at habel
  have hint : (∫ t in Set.Ioc X Y, deriv (fun s : ℝ => ((wLog s : ℝ) : ℂ)) t
        * ∑ k ∈ Finset.Icc 0 ⌊t⌋₊, ((vonMangoldt k : ℂ) * χ (k : ZMod q)))
      = ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ := by
    rw [intervalIntegral.integral_of_le hXY]
    refine setIntegral_congr_fun measurableSet_Ioc (fun t ht => ?_)
    rw [hderiv t ⟨le_of_lt ht.1, ht.2⟩, sum_Icc_zero_eq_psiChiR]
  rw [logChiSum, habel, hint]

/-- **The main term crosses the partial summation exactly.**  Integration by parts at
`u = 1/(t log t)`, `v = m·t^{β₀}/β₀`: the boundary terms and the `w'`-integral reassemble into
`m·∫_X^Y v^{β₀−2}/log v dv` with **no** error term. -/
lemma mainTerm_ibp {β₀ : ℝ} (hβ₀0 : 0 < β₀) (m : ℕ) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y) :
    (m : ℝ) * (∫ t in X..Y, t ^ (β₀ - 2) / Real.log t)
      = wLog Y * ((m : ℝ) * Y ^ β₀ / β₀) - wLog X * ((m : ℝ) * X ^ β₀ / β₀)
        - ∫ t in X..Y, wLog' t * ((m : ℝ) * t ^ β₀ / β₀) := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hβne : β₀ ≠ 0 := ne_of_gt hβ₀0
  have huIcc : Set.uIcc X Y = Set.Icc X Y := Set.uIcc_of_le hXY
  have hmemIcc : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hmem : ∀ t ∈ Set.uIcc X Y, (1 : ℝ) < t := by rw [huIcc]; exact hmemIcc
  have hu : ∀ t ∈ Set.uIcc X Y, HasDerivAt wLog (wLog' t) t :=
    fun t ht => hasDerivAt_wLog (hmem t ht)
  have hv : ∀ t ∈ Set.uIcc X Y,
      HasDerivAt (fun s : ℝ => (m : ℝ) * s ^ β₀ / β₀) ((m : ℝ) * t ^ (β₀ - 1)) t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmem t ht)
    have h1 : HasDerivAt (fun s : ℝ => s ^ β₀) (β₀ * t ^ (β₀ - 1)) t :=
      Real.hasDerivAt_rpow_const (Or.inl (ne_of_gt ht0))
    have h2 := (h1.const_mul (m : ℝ)).div_const β₀
    have heq : (m : ℝ) * (β₀ * t ^ (β₀ - 1)) / β₀ = (m : ℝ) * t ^ (β₀ - 1) := by
      field_simp
    rw [heq] at h2
    exact h2
  have hu' : IntervalIntegrable wLog' volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    exact (continuousOn_wLog' hmemIcc).integrableOn_compact isCompact_Icc
  have hv' : IntervalIntegrable (fun t : ℝ => (m : ℝ) * t ^ (β₀ - 1)) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    exact (continuousOn_const.mul (ContinuousOn.rpow_const continuousOn_id
      (fun t ht => Or.inl (ne_of_gt (lt_trans one_pos (hmemIcc t ht)))))).integrableOn_compact
      isCompact_Icc
  have hibp := intervalIntegral.integral_mul_deriv_eq_deriv_mul hu hv hu' hv'
  rw [← hibp, ← intervalIntegral.integral_const_mul]
  refine intervalIntegral.integral_congr (fun t ht => ?_)
  have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmem t ht)
  have hlt : 0 < Real.log t := Real.log_pos (hmem t ht)
  have hrp : t ^ (β₀ - 2) = t ^ (β₀ - 1) / t := by
    rw [show β₀ - 2 = (β₀ - 1) - 1 from by ring, Real.rpow_sub ht0, Real.rpow_one]
  rw [wLog, hrp]
  field_simp

/-- **THE COMPOSITE TRANSFER (N4b W2, design D3).**  A pointwise explicit-formula envelope on
`[X,Y]`,

    ‖ψ(t,χ) + m·t^{β₀}/β₀‖ ≤ t·G t,

partial-sums into HB's `(4.12)`:

    ‖∑_{X<n≤Y} χ(n)Λ(n)/(n log n) + m·∫_X^Y v^{β₀−2}/log v dv‖
      ≤ G X/log X + G Y/log Y + 2·∫_X^Y G t/(t log t) dt.

The exceptional zero's main term crosses the partial summation **exactly** — the integration by
parts `∫ w·(m t^{β₀−1}) = w(Y)M(Y) − w(X)M(X) − ∫ w'·M` is an identity, so no error at all is
charged to it; every term on the right is the envelope's own `dt/(t log t)` ledger.  This is the
`(4.12)`-form's multiplicative mandate: no free additive remainder reaches the consumer.

`m` rides explicitly (no simplicity hypothesis anywhere); `β₀` is real with `0 < β₀ < 1`. -/
theorem logChiSum_add_mainTerm_norm_le {q : ℕ} (χ : DirichletCharacter ℂ q)
    {β₀ : ℝ} (hβ₀0 : 0 < β₀) (m : ℕ) {X Y : ℝ} (hX : 3 ≤ X) (hXY : X ≤ Y)
    {G : ℝ → ℝ} (hGc : ContinuousOn G (Set.Icc X Y)) (hG0 : ∀ t ∈ Set.Icc X Y, 0 ≤ G t)
    (hEF : ∀ t ∈ Set.Icc X Y, ‖psiDefect χ β₀ m t‖ ≤ t * G t) :
    ‖logChiSum χ X Y + (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)‖
      ≤ G X / Real.log X + G Y / Real.log Y
        + 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
  have hX1 : (1 : ℝ) < X := by linarith
  have hY3 : (3 : ℝ) ≤ Y := le_trans hX hXY
  have huIcc : Set.uIcc X Y = Set.Icc X Y := Set.uIcc_of_le hXY
  have hmemIcc : ∀ t ∈ Set.Icc X Y, (1 : ℝ) < t := fun t ht => lt_of_lt_of_le hX1 ht.1
  have hXmem : X ∈ Set.Icc X Y := ⟨le_rfl, hXY⟩
  have hYmem : Y ∈ Set.Icc X Y := ⟨hXY, le_rfl⟩
  have hlog1 : ∀ t ∈ Set.Icc X Y, (1 : ℝ) ≤ Real.log t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
    have hte : Real.exp 1 ≤ t :=
      le_trans (le_of_lt (lt_trans Real.exp_one_lt_d9 (by norm_num))) (le_trans hX ht.1)
    exact (Real.le_log_iff_exp_le ht0).mpr hte
  -- the ℂ form of the exact main-term identity
  have hcast : (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ))
      = ((∫ t in X..Y, wLog' t * ((m : ℝ) * t ^ β₀ / β₀) : ℝ) : ℂ) := by
    rw [← intervalIntegral.integral_ofReal]
    exact intervalIntegral.integral_congr (fun t _ => by push_cast; ring)
  have hmain : (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)
      = ((wLog Y : ℝ) : ℂ) * (((m : ℝ) * Y ^ β₀ / β₀ : ℝ) : ℂ)
        - ((wLog X : ℝ) : ℂ) * (((m : ℝ) * X ^ β₀ / β₀ : ℝ) : ℂ)
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ) := by
    rw [hcast, show ((m : ℂ)) = (((m : ℝ)) : ℂ) from by push_cast; ring,
      ← Complex.ofReal_mul, mainTerm_ibp hβ₀0 m hX hXY]
    push_cast
    ring
  -- the three integrability facts
  have hcontFd : ContinuousOn (fun t : ℝ => ((wLog' t : ℝ) : ℂ)) (Set.Icc X Y) :=
    Complex.continuous_ofReal.comp_continuousOn (continuousOn_wLog' hmemIcc)
  have hIΨ : IntervalIntegrable (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * psiChiR t χ) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    have h0 := integrableOn_mul_sum_Icc (fun n : ℕ => ((vonMangoldt n : ℂ) * χ (n : ZMod q)))
      (m := 0) (b := Y) (by linarith : (0:ℝ) ≤ X)
      (hcontFd.integrableOn_compact isCompact_Icc)
    exact h0.congr_fun (fun t _ => by simp [sum_Icc_zero_eq_psiChiR]) measurableSet_Icc
  have hIM : IntervalIntegrable
      (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ)) volume X Y := by
    rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
    refine ContinuousOn.integrableOn_compact isCompact_Icc (hcontFd.mul ?_)
    refine Complex.continuous_ofReal.comp_continuousOn ?_
    exact ((continuousOn_const.mul (ContinuousOn.rpow_const continuousOn_id
      (fun t ht => Or.inl (ne_of_gt (lt_trans one_pos (hmemIcc t ht)))))).div_const β₀)
  have hID : IntervalIntegrable (fun t : ℝ => ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t)
      volume X Y := by
    refine (hIΨ.add hIM).congr (fun t _ => ?_)
    rw [psiDefect]; ring
  -- the exact assembly
  have hsplit : (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiChiR t χ)
      = (∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t)
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * (((m : ℝ) * t ^ β₀ / β₀ : ℝ) : ℂ) := by
    rw [← intervalIntegral.integral_sub hID hIM]
    exact intervalIntegral.integral_congr (fun t _ => by rw [psiDefect]; ring)
  have hkey : logChiSum χ X Y + (m : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)
      = ((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t := by
    rw [abel_logChiSum χ hX hXY, hmain, hsplit]
    simp only [psiDefect]
    ring
  rw [hkey]
  -- the three norm rows
  have hbdry : ∀ t ∈ Set.Icc X Y, ‖((wLog t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ G t / Real.log t := by
    intro t ht
    have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
    have hlt : (1 : ℝ) ≤ Real.log t := hlog1 t ht
    have hltpos : (0 : ℝ) < Real.log t := by linarith
    rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (wLog_nonneg (le_of_lt
      (hmemIcc t ht)))]
    calc wLog t * ‖psiDefect χ β₀ m t‖
        ≤ wLog t * (t * G t) :=
          mul_le_mul_of_nonneg_left (hEF t ht) (wLog_nonneg (le_of_lt (hmemIcc t ht)))
      _ = G t / Real.log t := by rw [wLog]; field_simp
  have hint : ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
    have hIG : IntervalIntegrable (fun t : ℝ => 2 * (G t / (t * Real.log t))) volume X Y := by
      rw [intervalIntegrable_iff_integrableOn_Icc_of_le hXY]
      refine ContinuousOn.integrableOn_compact isCompact_Icc (continuousOn_const.mul ?_)
      refine hGc.div (continuousOn_id.mul (Real.continuousOn_log.mono
        (fun t ht => ne_of_gt (lt_trans one_pos (hmemIcc t ht))))) ?_
      intro t ht
      have h1 := hmemIcc t ht
      have : 0 < Real.log t := Real.log_pos h1
      positivity
    calc ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
        ≤ ∫ t in X..Y, ‖((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ :=
          intervalIntegral.norm_integral_le_integral_norm hXY
      _ ≤ ∫ t in X..Y, 2 * (G t / (t * Real.log t)) := by
          refine intervalIntegral.integral_mono_on hXY hID.norm hIG (fun t ht => ?_)
          have ht0 : (0 : ℝ) < t := lt_trans one_pos (hmemIcc t ht)
          have hlt : (1 : ℝ) ≤ Real.log t := hlog1 t ht
          have hltpos : (0 : ℝ) < Real.log t := by linarith
          have hGt : 0 ≤ G t := hG0 t ht
          rw [norm_mul, Complex.norm_real, Real.norm_eq_abs,
            abs_of_nonpos (wLog'_nonpos (le_of_lt (hmemIcc t ht)))]
          have hw : -wLog' t = (Real.log t + 1) / (t * Real.log t) ^ 2 := by
            rw [wLog']; ring
          rw [hw]
          calc (Real.log t + 1) / (t * Real.log t) ^ 2 * ‖psiDefect χ β₀ m t‖
              ≤ (Real.log t + 1) / (t * Real.log t) ^ 2 * (t * G t) :=
                mul_le_mul_of_nonneg_left (hEF t ht) (by positivity)
            _ ≤ 2 * (G t / (t * Real.log t)) := by
                rw [div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
                have hsq : (t * Real.log t) ^ 2 = t * Real.log t * (t * Real.log t) := by ring
                rw [hsq]
                have hkey2 : (Real.log t + 1) * (t * G t) ≤ 2 * Real.log t * (t * G t) := by
                  nlinarith [mul_nonneg (le_of_lt ht0) hGt]
                calc (Real.log t + 1) * (t * G t)
                    ≤ 2 * Real.log t * (t * G t) := hkey2
                  _ = 2 * (G t / (t * Real.log t)) * (t * Real.log t * (t * Real.log t)) := by
                      field_simp
      _ = 2 * ∫ t in X..Y, G t / (t * Real.log t) := intervalIntegral.integral_const_mul _ _
  calc ‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X
        - ∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖
      ≤ ‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y - ((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X‖
          + ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ := norm_sub_le _ _
    _ ≤ (‖((wLog Y : ℝ) : ℂ) * psiDefect χ β₀ m Y‖
          + ‖((wLog X : ℝ) : ℂ) * psiDefect χ β₀ m X‖)
          + ‖∫ t in X..Y, ((wLog' t : ℝ) : ℂ) * psiDefect χ β₀ m t‖ :=
        add_le_add (norm_sub_le _ _) le_rfl
    _ ≤ (G Y / Real.log Y + G X / Real.log X) + 2 * ∫ t in X..Y, G t / (t * Real.log t) :=
        add_le_add (add_le_add (hbdry Y hYmem) (hbdry X hXmem)) hint
    _ = G X / Real.log X + G Y / Real.log Y + 2 * ∫ t in X..Y, G t / (t * Real.log t) := by
        ring

/-! ## 4. The explicit-formula side — the socket to `psiDefect` bridge -/

/-- **THE EF BRIDGE (N4b W2, design D1/D2/D4).**  The W0.5 socket
`psi_explicit_sharpM_perZero_unsep` (no well-spacing hypothesis: it pigeonholes internally)
composed with

* the `β₀` erase-split `efZeroSumM_erase_split` — which is **forced**, not merely convenient:
  the packaged `boxZeros_re_le_of_repulsion` cannot be used on a box containing `β₀` (its `hreal`
  demands every real zero of the box obey the repulsion ceiling, and `β₀` by construction does
  not);
* the A3-batched erased spend `efZeroSumM_norm_le_harmonic` × `efMultHarmonic_box_le` — the
  `log(qT)·log T` grade, never the `T·log(qT)` count;
* the same erase-split applied to the de-smoothing sum, so that `β₀`'s de-smoothing term keeps
  its own `u^{β₀−1}` and only the REST is charged the ceiling `bceil` (collapsing the whole sum to
  `efMultTotal·h` would be fatal — that term alone is `≈ 274·√T·log(qT)` relative).

The single carried ceiling binder is

    hceil : every zero `ρ ≠ β₀` of the strip `9/10 ≤ Re ρ ≤ 1`, `|Im ρ| ≤ T₀+1`, has `Re ρ ≤ bceil`,

which is exactly what the Range-A Deuring–Heilbronn ceiling (`dh_repulsion_tall` fed through the
`erase`-form of `boxZeros_re_le_of_repulsion`, under `hord`/`hreal′`/`hN+`) and the Range-B
`zero_free_region_all` ceiling supply; `hσbβ₀` is the statement that the `(1.11)` zero sits above
the contour window, and `hβ₀0` that it is a zero at all.  Nothing is silent: `m := zeroMult χ β₀`
rides explicitly, and the surviving `efShiftError` is the landed contour budget verbatim (its
explicit evaluation is the ledger row recorded in `docs/blueprints/flags.md`). -/
theorem psiDefect_norm_le_of_ef {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hq : 2 ≤ q) {β₀ bceil u h σa σb T₀ : ℝ}
    (hu : 3 ≤ u) (hh : 0 < h) (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hT₀ : 2 ≤ T₀) (hβ₀1 : β₀ ≤ 1) (hσbβ₀ : σb ≤ β₀)
    (hβ₀zero : LFunction χ (β₀ : ℂ) = 0)
    (hceil : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
      |ρ.im| ≤ T₀ + 1 → ρ.re ≤ bceil) :
    ∃ σ₀ T w : ℝ,
      (σa ≤ σ₀ ∧ σ₀ ≤ σb) ∧ (T₀ ≤ T ∧ T ≤ T₀ + 1) ∧ 0 < w ∧
      (σb - σa) / (4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1)) ≤ w ∧
      ‖psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u‖
        ≤ (h + 1) * Real.log (u + h)
          + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
          + ((zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
              + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))))
          + u ^ bceil * (137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1))) := by
  classical
  have hχ1 : χ ≠ 1 := ne_one_of_isPrimitive χ hχ hq
  have hu1 : (1 : ℝ) ≤ u := by linarith
  have hu0 : (0 : ℝ) < u := by linarith
  obtain ⟨σ₀, T, w, hσ, hT, hw, hwlb, hσ₀w, hσ₀1, hsock⟩ :=
    psi_explicit_sharpM_perZero_unsep χ hχ hq hu hh hσa hσab hσb hT₀
  refine ⟨σ₀, T, w, hσ, hT, hw, hwlb, ?_⟩
  have hT0 : (0 : ℝ) ≤ T := by linarith [hT.1]
  -- `β₀` lies in the contour box
  have hβZ : (β₀ : ℂ) ∈ boxZeros χ (σ₀ - w) 1 T := by
    rw [mem_boxZeros hχ1]
    refine ⟨hβ₀zero, ?_, ?_, ?_⟩
    · simp only [Complex.ofReal_re]; linarith [hσ.2]
    · simpa using hβ₀1
    · simp only [Complex.ofReal_im, abs_zero]; linarith [hT.1]
  -- the ceiling, on the ERASED box (the `hreal`-at-`β₀` repair)
  have hbar : ∀ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ), ρ.re ≤ bceil := by
    intro ρ hρ
    have hmem := (mem_boxZeros hχ1).mp (Finset.mem_of_mem_erase hρ)
    exact hceil ρ hmem.1 (Finset.ne_of_mem_erase hρ) (by linarith [hmem.2.1])
      hmem.2.2.1 (le_trans hmem.2.2.2 hT.2)
  -- the box's own strip data, for the A3 batching and the count
  have hZ0 : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, LFunction χ ρ = 0 :=
    fun ρ hρ => ((mem_boxZeros hχ1).mp hρ).1
  have hZre : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, 1 / 2 ≤ ρ.re ∧ ρ.re ≤ 1 := by
    intro ρ hρ
    have hmem := (mem_boxZeros hχ1).mp hρ
    exact ⟨by linarith [hmem.2.1], hmem.2.2.1⟩
  have hZim : ∀ ρ ∈ boxZeros χ (σ₀ - w) 1 T, |ρ.im| ≤ T :=
    fun ρ hρ => ((mem_boxZeros hχ1).mp hρ).2.2.2
  -- the exceptional residue is exactly `psiDefect`'s main term
  have hres : (((zeroMult χ (β₀ : ℂ) : ℝ) * u ^ β₀ / β₀ : ℝ) : ℂ)
      = (zeroMult χ (β₀ : ℂ) : ℂ) * (((u : ℝ) : ℂ) ^ (β₀ : ℂ) / (β₀ : ℂ)) := by
    push_cast [Complex.ofReal_cpow (le_of_lt hu0)]
    ring
  have hkey : psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u
      = (psiChiR u χ + efZeroSumM χ (boxZeros χ (σ₀ - w) 1 T) u)
        - efZeroSumM χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) u := by
    rw [efZeroSumM_erase_split χ hβZ u, psiDefect, hres]
    ring
  -- the A3-batched erased spend
  have hspend : ‖efZeroSumM χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) u‖
      ≤ u ^ bceil * (137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1))) := by
    refine le_trans (efZeroSumM_norm_le_harmonic χ hu1 hbar) ?_
    refine mul_le_mul_of_nonneg_left ?_ (Real.rpow_nonneg (by linarith) bceil)
    refine le_trans (Finset.sum_le_sum_of_subset_of_nonneg (Finset.erase_subset _ _)
      (fun i _ _ => div_nonneg (by positivity) (norm_nonneg i))) ?_
    exact efMultHarmonic_box_le χ hχ hq hT0 hZ0 hZre hZim
  -- the de-smoothing sum, `β₀` kept apart from the ceiling
  have hcount : efMultTotal χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ))
      ≤ 137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3)) := by
    refine le_trans (Finset.sum_le_sum_of_subset_of_nonneg (Finset.erase_subset _ _)
      (fun i _ _ => by positivity)) ?_
    exact zeroCountM_le χ hχ hq (by linarith : (1:ℝ)/2 ≤ σ₀ - w) hT0
  have hdesm : ∑ ρ ∈ boxZeros χ (σ₀ - w) 1 T, (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
      ≤ (zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
        + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) := by
    rw [← Finset.add_sum_erase _ (fun ρ => (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))) hβZ]
    simp only [Complex.ofReal_re]
    refine add_le_add le_rfl ?_
    calc ∑ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ),
          (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
        ≤ ∑ ρ ∈ (boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ),
            (zeroMult χ ρ : ℝ) * (h * u ^ (bceil - 1)) := by
          refine Finset.sum_le_sum (fun ρ hρ => ?_)
          refine mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left ?_ (le_of_lt hh))
            (by positivity)
          exact Real.rpow_le_rpow_of_exponent_le hu1 (by linarith [hbar ρ hρ])
      _ = efMultTotal χ ((boxZeros χ (σ₀ - w) 1 T).erase (β₀ : ℂ)) * (h * u ^ (bceil - 1)) := by
          rw [efMultTotal, Finset.sum_mul]
      _ ≤ (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) * (h * u ^ (bceil - 1)) := by
          refine mul_le_mul_of_nonneg_right hcount ?_
          have : (0:ℝ) < u ^ (bceil - 1) := Real.rpow_pos_of_pos hu0 _
          positivity
      _ = h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))) := by ring
  -- assembly
  rw [hkey]
  refine le_trans (norm_sub_le _ _) ?_
  have := le_trans hsock (by linarith [hdesm] :
    (h + 1) * Real.log (u + h)
      + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
      + ∑ ρ ∈ boxZeros χ (σ₀ - w) 1 T, (zeroMult χ ρ : ℝ) * (h * u ^ (ρ.re - 1))
    ≤ (h + 1) * Real.log (u + h)
      + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
      + ((zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
          + h * u ^ (bceil - 1) * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3)))))
  linarith [this, hspend]

/-! ## 5. Uniformising the contour budget over the pigeonholed parameters

`psi_explicit_sharpM_perZero_unsep` hands back `(σ₀, T, w)` from an internal pigeonhole, so an
envelope `G` — which must be a *function of `u` alone* — has to dominate `efShiftError q T σ₀ w ·`
uniformly over `σ₀ ∈ [σa,σb]`, `T ∈ [T₀,T₀+1]`, `w ≥ w₀`.  That is what this section does. -/

/-- `x^{c+1} = e·x²` at `c = 1 + 1/log x` — the one rpow identity the contour budget needs
(`efShiftError`'s two `x^{(1+1/log x)+1}` factors). -/
lemma rpow_c_add_one {x : ℝ} (hx : 3 ≤ x) :
    x ^ ((1 + 1 / Real.log x) + 1) = Real.exp 1 * x ^ (2 : ℕ) := by
  have hx0 : (0 : ℝ) < x := by linarith
  have hlogpos : (0 : ℝ) < Real.log x := Real.log_pos (by linarith)
  have hsplit : (1 + 1 / Real.log x) + 1 = (2 : ℝ) + 1 / Real.log x := by ring
  rw [hsplit, Real.rpow_add hx0, Real.rpow_def_of_pos hx0 (1 / Real.log x)]
  rw [show Real.log x * (1 / Real.log x) = 1 from by field_simp]
  rw [show (2 : ℝ) = ((2 : ℕ) : ℝ) from by norm_num, Real.rpow_natCast]
  ring

/-- **The uniform Borel–Carathéodory/Jensen edge constant** on the pigeonhole's parameter box:
`B = 120·L₄ + L₄/log(7/6)/w ≤ efShiftB q T₀ σa σb` whenever `T ≤ T₀+1` and `w ≥ w₀`. -/
noncomputable def efShiftB (q : ℕ) (T₀ σa σb : ℝ) : ℝ :=
  (120 + 4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1)
      / (Real.log (7 / 6) * (σb - σa)))
    * Real.log (4 * (5 * (5 + T₀) * Real.sqrt q * (1 + Real.log q)))

/-- **The uniform contour budget.**  `efShiftError q T σ₀ w x ≤ efShiftBound q T₀ σa σb x` for
every `(σ₀,T,w)` the pigeonhole can produce. -/
noncomputable def efShiftBound (q : ℕ) (T₀ σa σb x : ℝ) : ℝ :=
  (1 / (2 * Real.pi)) *
    (2 * ((1 + 1 / Real.log x) - σa) * efShiftB q T₀ σa σb * (Real.exp 1 * x ^ (2 : ℕ)) / T₀ ^ 2
      + efShiftB q T₀ σa σb * x ^ (σb + 1) * (Real.pi / σa)
      + (Real.log x + 1) * (Real.exp 1 * x ^ (2 : ℕ)) * (2 / T₀))

set_option maxHeartbeats 1000000 in
-- Three independent monotonicity rows, each a `mul_le_mul` chain over a five-factor product
-- (edge constant × rpow × 1/T-power), plus the `x^{c+1} = e·x²` rewrite; the elaborator needs
-- the same headroom the landed contour-shift assembly needed.
/-- **THE UNIFORMISATION (N4b W2, the ledger row's Lean form).**  Over the parameter box the
`exists_contour_params` pigeonhole ranges in, the landed contour budget is dominated by an
explicit function of `x` alone.  The three summands are, in order, the horizontal edges, the
left edge (`B·x^{σ₀+1}·π/σ₀` — D9's flagged row) and the truncation tail; the ledger row in
`docs/blueprints/flags.md` prices each of them at `T₀ = (log qx + 2)^6`. -/
theorem efShiftError_le_efShiftBound {q : ℕ} {T₀ σa σb T σ₀ w x : ℝ}
    (hq : 2 ≤ q) (hT₀ : 2 ≤ T₀) (hT : T₀ ≤ T) (hT2 : T ≤ T₀ + 1)
    (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hσ0a : σa ≤ σ₀) (hσ0b : σ₀ ≤ σb) (hw : 0 < w)
    (hwlb : (σb - σa) / (4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1)) ≤ w)
    (hx : 3 ≤ x) :
    efShiftError q T σ₀ w x ≤ efShiftBound q T₀ σa σb x := by
  have hx0 : (0 : ℝ) < x := by linarith
  have hx1 : (1 : ℝ) ≤ x := by linarith
  have hlogpos : (0 : ℝ) < Real.log x := Real.log_pos (by linarith)
  have hq1 : (1 : ℝ) ≤ (q : ℝ) := by exact_mod_cast Nat.one_le_of_lt hq
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hT0pos : (0 : ℝ) < T₀ := by linarith
  have hTpos : (0 : ℝ) < T := by linarith
  have hσapos : (0 : ℝ) < σa := by linarith
  have hσ0pos : (0 : ℝ) < σ₀ := by linarith
  have hba : (0 : ℝ) < σb - σa := by linarith
  have hlog76 : (0 : ℝ) < Real.log (7 / 6) := Real.log_pos (by norm_num)
  have hsq : (1 : ℝ) ≤ Real.sqrt q := by
    rw [show (1 : ℝ) = Real.sqrt 1 from (Real.sqrt_one).symm]
    exact Real.sqrt_le_sqrt hq1
  have hlogq : (0 : ℝ) ≤ Real.log q := Real.log_nonneg hq1
  -- the two `L₄`s and their comparison
  set L4 : ℝ := Real.log (4 * (5 * (4 + T) * Real.sqrt q * (1 + Real.log q))) with hL4
  set L4' : ℝ := Real.log (4 * (5 * (5 + T₀) * Real.sqrt q * (1 + Real.log q))) with hL4'
  have hprod : (30 : ℝ) ≤ 5 * (4 + T) * Real.sqrt q * (1 + Real.log q) := by
    have h1 : (30 : ℝ) * 1 ≤ 5 * (4 + T) * Real.sqrt q :=
      mul_le_mul (by linarith) hsq (by norm_num) (by linarith)
    have h2 : (30 : ℝ) * 1 ≤ 5 * (4 + T) * Real.sqrt q * (1 + Real.log q) :=
      mul_le_mul (by linarith) (by linarith) (by norm_num) (by linarith)
    linarith
  have hinner : (1 : ℝ) ≤ 4 * (5 * (4 + T) * Real.sqrt q * (1 + Real.log q)) := by linarith
  have hL4nn : 0 ≤ L4 := Real.log_nonneg hinner
  have hL4le : L4 ≤ L4' := by
    refine Real.log_le_log (by linarith) ?_
    have hs : (0 : ℝ) ≤ Real.sqrt q * (1 + Real.log q) := by positivity
    have h1 : 5 * (4 + T) * (Real.sqrt q * (1 + Real.log q))
        ≤ 5 * (5 + T₀) * (Real.sqrt q * (1 + Real.log q)) :=
      mul_le_mul_of_nonneg_right (by linarith) hs
    nlinarith [h1]
  have hL4'nn : 0 ≤ L4' := le_trans hL4nn hL4le
  -- the edge constant
  set K : ℝ := 4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1) with hK
  have hlogK : (0 : ℝ) ≤ Real.log ((q : ℝ) * (T₀ + 5)) := by
    refine Real.log_nonneg ?_
    nlinarith
  have hKpos : (0 : ℝ) < K := by
    have h := mul_nonneg (mul_nonneg (by norm_num : (0:ℝ) ≤ 137)
      (by linarith : (0:ℝ) ≤ 2 * T₀ + 7)) hlogK
    rw [hK]; linarith
  have hinvw : 1 / w ≤ K / (σb - σa) := by
    rw [div_le_div_iff₀ hw hba]
    rw [div_le_iff₀ hKpos] at hwlb
    nlinarith [hwlb]
  have hcnn : (0 : ℝ) ≤ 120 * L4 + L4 / Real.log (7 / 6) / w :=
    add_nonneg (by linarith)
      (div_nonneg (div_nonneg hL4nn (le_of_lt hlog76)) (le_of_lt hw))
  have hB : 120 * L4 + L4 / Real.log (7 / 6) / w ≤ efShiftB q T₀ σa σb := by
    have h1 : L4 / Real.log (7 / 6) / w = (L4 / Real.log (7 / 6)) * (1 / w) := by
      rw [div_eq_mul_inv]; ring
    have hstep : (L4 / Real.log (7 / 6)) * (1 / w)
        ≤ (L4' / Real.log (7 / 6)) * (K / (σb - σa)) :=
      mul_le_mul (by gcongr) hinvw (by positivity) (div_nonneg hL4'nn (le_of_lt hlog76))
    have h4 : (L4' / Real.log (7 / 6)) * (K / (σb - σa))
        = K / (Real.log (7 / 6) * (σb - σa)) * L4' := by field_simp
    rw [h4] at hstep
    have hgoal : efShiftB q T₀ σa σb
        = 120 * L4' + K / (Real.log (7 / 6) * (σb - σa)) * L4' := by
      rw [efShiftB, ← hL4', ← hK]; ring
    rw [hgoal, h1]
    linarith [hstep, hL4le]
  have hBnn : 0 ≤ efShiftB q T₀ σa σb := le_trans hcnn hB
  -- the three rows
  rw [efShiftError, efShiftBound, ← hL4, rpow_c_add_one hx]
  have hex : (0 : ℝ) < Real.exp 1 * x ^ (2 : ℕ) := by positivity
  have hπ : (0 : ℝ) < Real.pi := Real.pi_pos
  have hcx : (0 : ℝ) < 1 / Real.log x := by positivity
  refine mul_le_mul_of_nonneg_left (add_le_add (add_le_add ?_ ?_) ?_) (by positivity)
  · -- the horizontal edges
    have hnum : 2 * ((1 + 1 / Real.log x) - σ₀) * (120 * L4 + L4 / Real.log (7 / 6) / w)
          * (Real.exp 1 * x ^ (2 : ℕ))
        ≤ 2 * ((1 + 1 / Real.log x) - σa) * efShiftB q T₀ σa σb
          * (Real.exp 1 * x ^ (2 : ℕ)) := by
      have ha : (0 : ℝ) ≤ 2 * ((1 + 1 / Real.log x) - σ₀) := by linarith
      have hb : 2 * ((1 + 1 / Real.log x) - σ₀) ≤ 2 * ((1 + 1 / Real.log x) - σa) := by linarith
      have hstep : 2 * ((1 + 1 / Real.log x) - σ₀) * (120 * L4 + L4 / Real.log (7 / 6) / w)
          ≤ 2 * ((1 + 1 / Real.log x) - σa) * efShiftB q T₀ σa σb :=
        mul_le_mul hb hB hcnn (by linarith)
      exact mul_le_mul_of_nonneg_right hstep (le_of_lt hex)
    have hnum0 : (0 : ℝ) ≤ 2 * ((1 + 1 / Real.log x) - σ₀) * (120 * L4
        + L4 / Real.log (7 / 6) / w) * (Real.exp 1 * x ^ (2 : ℕ)) := by
      have : (0 : ℝ) ≤ 2 * ((1 + 1 / Real.log x) - σ₀) := by linarith
      have h2 := mul_nonneg this hcnn
      exact mul_nonneg h2 (le_of_lt hex)
    have hTsq : T₀ ^ 2 ≤ T ^ 2 := by nlinarith
    rw [div_le_div_iff₀ (by positivity) (by positivity)]
    nlinarith [hnum, hnum0, hTsq]
  · -- the left edge (D9's flagged row)
    have hxr : x ^ (σ₀ + 1) ≤ x ^ (σb + 1) :=
      Real.rpow_le_rpow_of_exponent_le hx1 (by linarith)
    have hxp : (0 : ℝ) < x ^ (σ₀ + 1) := Real.rpow_pos_of_pos hx0 _
    have hxp' : (0 : ℝ) < x ^ (σb + 1) := Real.rpow_pos_of_pos hx0 _
    have hσinv : Real.pi / σ₀ ≤ Real.pi / σa :=
      div_le_div_of_nonneg_left (le_of_lt hπ) hσapos hσ0a
    have hstep1 : (120 * L4 + L4 / Real.log (7 / 6) / w) * x ^ (σ₀ + 1)
        ≤ efShiftB q T₀ σa σb * x ^ (σb + 1) :=
      mul_le_mul hB hxr (le_of_lt hxp) hBnn
    exact mul_le_mul hstep1 hσinv (by positivity) (mul_nonneg hBnn (le_of_lt hxp'))
  · -- the truncation tail
    have h2T : (2 : ℝ) / T ≤ 2 / T₀ := div_le_div_of_nonneg_left (by norm_num) hT0pos hT
    have hlgnn : (0 : ℝ) ≤ (Real.log x + 1) * (Real.exp 1 * x ^ (2 : ℕ)) := by
      have : (0 : ℝ) ≤ Real.log x + 1 := by linarith
      exact mul_nonneg this (le_of_lt hex)
    exact mul_le_mul_of_nonneg_left h2T hlgnn

/-! ## 6. Discharging the ceiling binder — the two ranges (W2b, part (b))

`psiDefect_norm_le_of_ef` carries one abstract ceiling binder `hceil`.  This section discharges
it, in the freeze's two ranges, against the landed artillery.  The Range-A stone is the
**`erase`-form** of `boxZeros_re_le_of_repulsion`: the packaged version cannot be used at all on a
box containing `β₀`, because its `hreal` demands every real box zero obey the repulsion ceiling
and `β₀` by construction does not.  Here `hreal′` carries the escape `ρ ≠ β₀` explicitly, and
`hord` (T-BAL-UNORDERED) and `hN+` (D2's regime form) enter the block as named binders. -/

/-- **RANGE A — the Deuring–Heilbronn ceiling, `β₀` excepted** (the `erase`-form).  Every zero of
`L(·,χ)` other than `β₀` in the strip `9/10 ≤ Re ρ ≤ 1`, `|Im ρ| ≤ T` obeys the repulsion ceiling
at the box top `Q = q(T+2)`.  `hrep` is `dh_repulsion_tall`'s contract specialised at `χ, β₀`
(height-free, so no `|Im ρ| ≤ T` appears in it); `hord` is the named T-BAL-UNORDERED deviation;
`hreal′` is the real-zero binder RESTATED over the erased box (D4); `hN` is `hN+`'s
non-vacuousness statement at the box top; `hceil16` covers the discarded strip `Re ρ < 16/17`
for free. -/
theorem re_le_repulsionCeiling_of_ne {q : ℕ} [NeZero q] {χ : DirichletCharacter ℂ q}
    (hχ1 : χ ≠ 1) {b c k β₀ T : ℝ} (hb : 0 < b) (hc : 0 < c) (hk : 0 ≤ k)
    (hq : 2 ≤ q) (hβ₀1 : β₀ < 1)
    (hrep : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ.im ≠ 0 → 16 / 17 ≤ ρ.re → ρ.re < 1 → ρ.re ≤ β₀ →
      c * ((q : ℝ) * (|ρ.im| + 2)) ^ (-(b * (1 - ρ.re)))
        / (Real.log ((q : ℝ) * (|ρ.im| + 2)) + 2) ^ k ≤ 1 - β₀)
    (hord : ∀ ρ : ℂ, LFunction χ ρ = 0 → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T → ρ.re ≤ β₀)
    (hreal : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ.im = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
      |ρ.im| ≤ T → ρ.re ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀))
    (hceil16 : 16 / 17 ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀))
    (hN : 0 ≤ Real.log (1 / (1 - β₀)) - Real.log (1 / c)
      - k * Real.log (Real.log ((q : ℝ) * (T + 2)) + 2)) :
    ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T →
      ρ.re ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀) := by
  intro ρ hzero hne hlo hhi him
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hu : (0 : ℝ) < 1 - β₀ := by linarith
  have hlt1 : ρ.re < 1 := by
    rcases lt_or_eq_of_le hhi with h | h
    · exact h
    · exact absurd hzero (LFunction_ne_zero_of_one_le_re χ (Or.inl hχ1) (le_of_eq h.symm))
  rcases le_or_gt (16 / 17 : ℝ) ρ.re with hwin | hwin
  · rcases eq_or_ne ρ.im 0 with hre0 | hre0
    · exact hreal ρ hzero hre0 hne hlo hhi him
    · have hQρ1 : (1 : ℝ) < (q : ℝ) * (|ρ.im| + 2) := by nlinarith [abs_nonneg ρ.im]
      have hQρle : (q : ℝ) * (|ρ.im| + 2) ≤ (q : ℝ) * (T + 2) := by
        nlinarith [abs_nonneg ρ.im]
      have hstep := repulsion_ceiling_of_contract (σ := ρ.re) hb hc hQρ1 hu
        (hrep ρ hzero hre0 hwin hlt1 (hord ρ hzero hlo hhi him))
      exact le_trans hstep (repulsionCeiling_mono hb hk hQρ1 hQρle hN)
  · linarith [hceil16]

/-- **RANGE A, packaged off `dh_repulsion_tall`.**  The artillery's own `(b,c,k)` — the
height-free contract — delivered together with the erased-box ceiling it forces, at every height
`T`.  `hord`/`hreal′`/`hN+` ride as named binders exactly as the freeze's §1 says. -/
theorem exists_repulsion_ceiling_of_ne {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hχ1 : χ ≠ 1) (hχ2 : χ ^ 2 = 1) (hq : 2 ≤ q) {β₀ : ℝ}
    (hβ₀zero : LFunction χ (β₀ : ℂ) = 0) (hβ₀half : 1 / 2 < β₀) (hβ₀1 : β₀ < 1) :
    ∃ b c k : ℝ, 0 < b ∧ 0 < c ∧ 0 ≤ k ∧
      ∀ T : ℝ,
        (∀ ρ : ℂ, LFunction χ ρ = 0 → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T → ρ.re ≤ β₀) →
        (∀ ρ : ℂ, LFunction χ ρ = 0 → ρ.im = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
          |ρ.im| ≤ T → ρ.re ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀)) →
        16 / 17 ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀) →
        0 ≤ Real.log (1 / (1 - β₀)) - Real.log (1 / c)
          - k * Real.log (Real.log ((q : ℝ) * (T + 2)) + 2) →
        ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T →
          ρ.re ≤ repulsionCeiling b c k ((q : ℝ) * (T + 2)) (1 - β₀) := by
  obtain ⟨b, c, k, hb, hc, hk, hDH⟩ := dh_repulsion_tall
  refine ⟨b, c, k, hb, hc, hk, fun T hord hreal hceil16 hN => ?_⟩
  exact re_le_repulsionCeiling_of_ne hχ1 hb hc hk hq hβ₀1
    (fun ρ hz him hwin hlt hle =>
      hDH q χ hχ hχ1 hχ2 hq β₀ hβ₀zero hβ₀half hβ₀1 ρ hz him hwin hlt hle)
    hord hreal hceil16 hN

/-- **RANGE B — the classical zero-free region, `β₀` excepted.**  Above `Y₁` the repulsion
contract goes vacuous (its `−k·log(log Q + 2)` correction eats the numerator), and D4's fallback
is `zero_free_region_all`.  That region covers ONLY the complex zeros of a real character — its
side condition `χ² ≠ 1 ∨ Im ρ ≠ 0` excludes the real ones — so `hreal′` is carried here too,
at whatever ceiling the caller supplies (D4: the repulsion ceiling, the stronger of the two, so
ONE binder serves both ranges). -/
theorem re_le_of_zeroFree_of_ne {q : ℕ} [NeZero q] {χ : DirichletCharacter ℂ q}
    {c₀ β₀ T bc : ℝ} (hq : 2 ≤ q) (hc₀ : 0 < c₀)
    (hZFR : ∀ ρ : ℂ, LFunction χ ρ = 0 → 1 / 2 ≤ ρ.re → (χ ^ 2 ≠ 1 ∨ ρ.im ≠ 0) →
      ρ.re ≤ 1 - c₀ / Real.log ((q : ℝ) * (|ρ.im| + 2)))
    (hreal : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ.im = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
      |ρ.im| ≤ T → ρ.re ≤ bc)
    (hbc : 1 - c₀ / Real.log ((q : ℝ) * (T + 2)) ≤ bc) :
    ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T →
      ρ.re ≤ bc := by
  intro ρ hzero hne hlo hhi him
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  rcases eq_or_ne ρ.im 0 with hre0 | hre0
  · exact hreal ρ hzero hre0 hne hlo hhi him
  · have h := hZFR ρ hzero (by linarith) (Or.inr hre0)
    have hQ1 : (1 : ℝ) < (q : ℝ) * (|ρ.im| + 2) := by nlinarith [abs_nonneg ρ.im]
    have hQ2 : (q : ℝ) * (|ρ.im| + 2) ≤ (q : ℝ) * (T + 2) := by nlinarith [abs_nonneg ρ.im]
    have hl1 : (0 : ℝ) < Real.log ((q : ℝ) * (|ρ.im| + 2)) := Real.log_pos hQ1
    have hl2 : Real.log ((q : ℝ) * (|ρ.im| + 2)) ≤ Real.log ((q : ℝ) * (T + 2)) :=
      Real.log_le_log (by linarith) hQ2
    have hdiv : c₀ / Real.log ((q : ℝ) * (T + 2)) ≤ c₀ / Real.log ((q : ℝ) * (|ρ.im| + 2)) :=
      div_le_div_of_nonneg_left (le_of_lt hc₀) hl1 hl2
    linarith

/-- **THE COMPOSITE WITH `hceil` DISCHARGED, RANGE A.**  `psiDefect_norm_le_of_ef` fired at the
repulsion ceiling: `hceil` is replaced by `hord`, `hreal′` and `hN+` — the freeze's own binder
set — with the artillery's `(b,c,k)` obtained from `dh_repulsion_tall`. -/
theorem psiDefect_norm_le_rangeA {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hχ2 : χ ^ 2 = 1) (hq : 2 ≤ q) {β₀ u h σa σb T₀ : ℝ}
    (hu : 3 ≤ u) (hh : 0 < h) (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hT₀ : 2 ≤ T₀) (hβ₀half : 1 / 2 < β₀) (hβ₀1 : β₀ < 1) (hσbβ₀ : σb ≤ β₀)
    (hβ₀zero : LFunction χ (β₀ : ℂ) = 0) :
    ∃ b c k : ℝ, 0 < b ∧ 0 < c ∧ 0 ≤ k ∧
      ((∀ ρ : ℂ, LFunction χ ρ = 0 → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 → |ρ.im| ≤ T₀ + 1 → ρ.re ≤ β₀) →
       (∀ ρ : ℂ, LFunction χ ρ = 0 → ρ.im = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
          |ρ.im| ≤ T₀ + 1 →
          ρ.re ≤ repulsionCeiling b c k ((q : ℝ) * (T₀ + 3)) (1 - β₀)) →
       16 / 17 ≤ repulsionCeiling b c k ((q : ℝ) * (T₀ + 3)) (1 - β₀) →
       0 ≤ Real.log (1 / (1 - β₀)) - Real.log (1 / c)
          - k * Real.log (Real.log ((q : ℝ) * (T₀ + 3)) + 2) →
       ∃ σ₀ T w : ℝ,
        (σa ≤ σ₀ ∧ σ₀ ≤ σb) ∧ (T₀ ≤ T ∧ T ≤ T₀ + 1) ∧ 0 < w ∧
        (σb - σa) / (4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1)) ≤ w ∧
        ‖psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u‖
          ≤ (h + 1) * Real.log (u + h)
            + (efShiftError q T σ₀ w u + efShiftError q T σ₀ w (u + h)) / h
            + ((zeroMult χ (β₀ : ℂ) : ℝ) * (h * u ^ (β₀ - 1))
                + h * u ^ (repulsionCeiling b c k ((q : ℝ) * (T₀ + 3)) (1 - β₀) - 1)
                  * (137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))))
            + u ^ (repulsionCeiling b c k ((q : ℝ) * (T₀ + 3)) (1 - β₀))
              * (137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1)))) := by
  have hχ1 : χ ≠ 1 := ne_one_of_isPrimitive χ hχ hq
  obtain ⟨b, c, k, hb, hc, hk, hceilA⟩ :=
    exists_repulsion_ceiling_of_ne χ hχ hχ1 hχ2 hq hβ₀zero hβ₀half hβ₀1
  refine ⟨b, c, k, hb, hc, hk, fun hord hreal hceil16 hN => ?_⟩
  have hbase : (q : ℝ) * (T₀ + 1 + 2) = (q : ℝ) * (T₀ + 3) := by ring
  exact psiDefect_norm_le_of_ef χ hχ hq hu hh hσa hσab hσb hT₀ (le_of_lt hβ₀1) hσbβ₀ hβ₀zero
    (by
      have := hceilA (T₀ + 1) hord (by rw [hbase]; exact hreal) (by rw [hbase]; exact hceil16)
        (by rw [hbase]; exact hN)
      rw [hbase] at this
      exact this)

/-! ## 7. The closed-form envelope at the design parameters (W2b, part (a))

The freeze's D1 parameters: the growing truncation height `T₀(u) = (log(qu) + 2)^6` and the
de-smoothing step `h(u) = u/√(T₀(u)) = u/(log(qu) + 2)^3` (the square root is exact, which is why
the exponent `6` is written as it is).  Everything the EF bridge produces is then dominated by a
function of `u` ALONE — the socket's `(σ₀, T, w)` are eliminated by `efShiftError_le_efShiftBound`
and by the `T`-monotonicity of the two count rows. -/

/-- The design height `T₀(u) = (log(q·u) + 2)^6` (freeze D1; the ledger row in
`docs/blueprints/flags.md` fixes the exponent `6`). -/
noncomputable def efT0 (q : ℕ) (u : ℝ) : ℝ := (Real.log ((q : ℝ) * u) + 2) ^ 6

/-- The de-smoothing step `h(u) = u/√(T₀(u)) = u/(log(q·u) + 2)^3`. -/
noncomputable def efH (q : ℕ) (u : ℝ) : ℝ := u / (Real.log ((q : ℝ) * u) + 2) ^ 3

lemma two_le_efT0 {q : ℕ} {u : ℝ} (hq : 2 ≤ q) (hu : 3 ≤ u) : 2 ≤ efT0 q u := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hqu : (6 : ℝ) ≤ (q : ℝ) * u := by nlinarith
  have hlog : (1 : ℝ) ≤ Real.log ((q : ℝ) * u) := by
    have he : Real.exp 1 ≤ (q : ℝ) * u :=
      le_trans (le_of_lt (lt_trans Real.exp_one_lt_d9 (by norm_num))) hqu
    exact (Real.le_log_iff_exp_le (by linarith)).mpr he
  rw [efT0]
  nlinarith [pow_le_pow_left₀ (by norm_num : (0:ℝ) ≤ 3)
    (by linarith : (3:ℝ) ≤ Real.log ((q : ℝ) * u) + 2) 6]

lemma efH_pos {q : ℕ} {u : ℝ} (hq : 2 ≤ q) (hu : 3 ≤ u) : 0 < efH q u := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hqu : (6 : ℝ) ≤ (q : ℝ) * u := by nlinarith
  have hlog : (0 : ℝ) ≤ Real.log ((q : ℝ) * u) := Real.log_nonneg (by linarith)
  rw [efH]
  apply div_pos (by linarith)
  positivity

/-- **THE ENVELOPE `G`** — the closed form of HB's relative explicit-formula error at the design
parameters, a function of `u` alone.  The four groups are, in order: the de-smoothing boundary
`(h+1)log(u+h)`, the uniformised contour budget `(E(u)+E(u+h))/h`, the de-smoothing zero mass
(`β₀`'s own term kept apart from the ceiling — collapsing them is fatal), and the A3-batched
erased spend.  The `/u` at the end is the relative normalisation `logChiSum_add_mainTerm_norm_le`
consumes. -/
noncomputable def efEnvelope (q : ℕ) (β₀ bceil : ℝ) (m : ℕ) (σa σb u : ℝ) : ℝ :=
  ((efH q u + 1) * Real.log (u + efH q u)
    + (efShiftBound q (efT0 q u) σa σb u + efShiftBound q (efT0 q u) σa σb (u + efH q u))
        / efH q u
    + ((m : ℝ) * (efH q u * u ^ (β₀ - 1))
        + efH q u * u ^ (bceil - 1)
          * (137 * (2 * efT0 q u + 5) * Real.log ((q : ℝ) * (efT0 q u + 4))))
    + u ^ bceil * (137 * Real.log ((q : ℝ) * (efT0 q u + 4))
        * (8 + 4 * Real.log (efT0 q u + 2)))) / u

/-- **THE ENVELOPE BOUND (N4b W2b, part (a)).**  `‖ψ(u,χ) + m·u^{β₀}/β₀‖ ≤ u·G(u)` at
`G = efEnvelope`, the exact hypothesis `logChiSum_add_mainTerm_norm_le` demands.  The socket's
pigeonholed `(σ₀,T,w)` are gone: the contour budget by `efShiftError_le_efShiftBound`, the two
count rows by `T`-monotonicity at `T ≤ T₀+1`. -/
theorem psiDefect_norm_le_envelope {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hq : 2 ≤ q) {β₀ bceil u σa σb : ℝ}
    (hu : 3 ≤ u) (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hβ₀1 : β₀ ≤ 1) (hσbβ₀ : σb ≤ β₀) (hβ₀zero : LFunction χ (β₀ : ℂ) = 0)
    (hceil : ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re → ρ.re ≤ 1 →
      |ρ.im| ≤ efT0 q u + 1 → ρ.re ≤ bceil) :
    ‖psiDefect χ β₀ (zeroMult χ (β₀ : ℂ)) u‖
      ≤ u * efEnvelope q β₀ bceil (zeroMult χ (β₀ : ℂ)) σa σb u := by
  have hu0 : (0 : ℝ) < u := by linarith
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hT0 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
  have hHpos : 0 < efH q u := efH_pos hq hu
  have huh : (3 : ℝ) ≤ u + efH q u := by linarith
  obtain ⟨σ₀, T, w, hσ, hT, hw, hwlb, hbnd⟩ :=
    psiDefect_norm_le_of_ef χ hχ hq hu hHpos hσa hσab hσb hT0 hβ₀1 hσbβ₀ hβ₀zero hceil
  refine le_trans hbnd ?_
  -- unfold the relative normalisation
  have hnorm : u * efEnvelope q β₀ bceil (zeroMult χ (β₀ : ℂ)) σa σb u
      = (efH q u + 1) * Real.log (u + efH q u)
        + (efShiftBound q (efT0 q u) σa σb u
            + efShiftBound q (efT0 q u) σa σb (u + efH q u)) / efH q u
        + ((zeroMult χ (β₀ : ℂ) : ℝ) * (efH q u * u ^ (β₀ - 1))
            + efH q u * u ^ (bceil - 1)
              * (137 * (2 * efT0 q u + 5) * Real.log ((q : ℝ) * (efT0 q u + 4))))
        + u ^ bceil * (137 * Real.log ((q : ℝ) * (efT0 q u + 4))
            * (8 + 4 * Real.log (efT0 q u + 2))) := by
    rw [efEnvelope]; field_simp
  rw [hnorm]
  -- the two `T`-monotone count rows
  have hTb : T ≤ efT0 q u + 1 := hT.2
  have hTpos : (0 : ℝ) < T := by linarith [hT.1]
  have hqT1 : (1 : ℝ) ≤ (q : ℝ) * (T + 3) := by nlinarith
  have hlogT : (0 : ℝ) ≤ Real.log ((q : ℝ) * (T + 3)) := Real.log_nonneg hqT1
  have hlogTle : Real.log ((q : ℝ) * (T + 3)) ≤ Real.log ((q : ℝ) * (efT0 q u + 4)) := by
    refine Real.log_le_log (by linarith) ?_
    nlinarith
  have hlogT1 : (0 : ℝ) ≤ Real.log (T + 1) := Real.log_nonneg (by linarith)
  have hlogT1le : Real.log (T + 1) ≤ Real.log (efT0 q u + 2) :=
    Real.log_le_log (by linarith) (by linarith)
  have hrow3 : 137 * (2 * T + 3) * Real.log ((q : ℝ) * (T + 3))
      ≤ 137 * (2 * efT0 q u + 5) * Real.log ((q : ℝ) * (efT0 q u + 4)) :=
    mul_le_mul (by linarith) hlogTle hlogT (by linarith)
  have hrow4 : 137 * Real.log ((q : ℝ) * (T + 3)) * (8 + 4 * Real.log (T + 1))
      ≤ 137 * Real.log ((q : ℝ) * (efT0 q u + 4)) * (8 + 4 * Real.log (efT0 q u + 2)) :=
    mul_le_mul (by linarith) (by linarith) (by linarith) (by linarith)
  refine add_le_add (add_le_add (add_le_add le_rfl ?_) ?_) ?_
  · -- the uniformised contour budget
    have hE1 : efShiftError q T σ₀ w u ≤ efShiftBound q (efT0 q u) σa σb u :=
      efShiftError_le_efShiftBound hq hT0 hT.1 hT.2 hσa hσab hσb hσ.1 hσ.2 hw hwlb hu
    have hE2 : efShiftError q T σ₀ w (u + efH q u)
        ≤ efShiftBound q (efT0 q u) σa σb (u + efH q u) :=
      efShiftError_le_efShiftBound hq hT0 hT.1 hT.2 hσa hσab hσb hσ.1 hσ.2 hw hwlb huh
    exact div_le_div_of_nonneg_right (by linarith) (le_of_lt hHpos)
  · -- the de-smoothing zero mass
    refine add_le_add le_rfl (mul_le_mul_of_nonneg_left hrow3 ?_)
    have : (0 : ℝ) < u ^ (bceil - 1) := Real.rpow_pos_of_pos hu0 _
    positivity
  · -- the A3-batched erased spend
    exact mul_le_mul_of_nonneg_left hrow4 (le_of_lt (Real.rpow_pos_of_pos hu0 bceil))

/-! ### The envelope is continuous — the last hypothesis of the transfer -/

private lemma cont_log_comp {s : Set ℝ} {g : ℝ → ℝ} (hg : ContinuousOn g s)
    (h0 : ∀ x ∈ s, g x ≠ 0) : ContinuousOn (fun x => Real.log (g x)) s :=
  Real.continuousOn_log.comp hg (fun x hx => by simpa using h0 x hx)

private lemma cont_logqu {q : ℕ} (hq : 2 ≤ q) :
    ContinuousOn (fun u : ℝ => Real.log ((q : ℝ) * u)) (Set.Ici (3 : ℝ)) := by
  have hq0 : (0 : ℝ) < (q : ℝ) := by
    have : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
    linarith
  refine cont_log_comp (continuousOn_const.mul continuousOn_id) (fun u hu => ?_)
  have h3 : (3 : ℝ) ≤ u := hu
  exact ne_of_gt (by positivity)

private lemma logqu_ge {q : ℕ} (hq : 2 ≤ q) {u : ℝ} (hu : 3 ≤ u) :
    (3 : ℝ) ≤ Real.log ((q : ℝ) * u) + 2 := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hqu : (6 : ℝ) ≤ (q : ℝ) * u := by nlinarith
  have he : Real.exp 1 ≤ (q : ℝ) * u :=
    le_trans (le_of_lt (lt_trans Real.exp_one_lt_d9 (by norm_num))) hqu
  have : (1 : ℝ) ≤ Real.log ((q : ℝ) * u) := (Real.le_log_iff_exp_le (by linarith)).mpr he
  linarith

private lemma cont_efT0 {q : ℕ} (hq : 2 ≤ q) :
    ContinuousOn (fun u : ℝ => efT0 q u) (Set.Ici (3 : ℝ)) := by
  simp only [efT0]
  exact ((cont_logqu hq).add continuousOn_const).pow 6

private lemma cont_efH {q : ℕ} (hq : 2 ≤ q) :
    ContinuousOn (fun u : ℝ => efH q u) (Set.Ici (3 : ℝ)) := by
  simp only [efH]
  refine continuousOn_id.div (((cont_logqu hq).add continuousOn_const).pow 3) (fun u hu => ?_)
  have h := logqu_ge hq (show (3:ℝ) ≤ u from hu)
  positivity

private lemma cont_logQT {q : ℕ} (hq : 2 ≤ q) (a : ℝ) (ha : 0 ≤ a) :
    ContinuousOn (fun u : ℝ => Real.log ((q : ℝ) * (efT0 q u + a))) (Set.Ici (3 : ℝ)) := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  refine cont_log_comp (continuousOn_const.mul ((cont_efT0 hq).add continuousOn_const))
    (fun u hu => ne_of_gt ?_)
  have h1 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
  nlinarith

private lemma cont_efShiftB {q : ℕ} (hq : 2 ≤ q) {σa σb : ℝ} :
    ContinuousOn (fun u : ℝ => efShiftB q (efT0 q u) σa σb) (Set.Ici (3 : ℝ)) := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hsq : (1 : ℝ) ≤ Real.sqrt q := by
    rw [show (1 : ℝ) = Real.sqrt 1 from (Real.sqrt_one).symm]
    exact Real.sqrt_le_sqrt (by linarith)
  have hlq : (0 : ℝ) ≤ Real.log q := Real.log_nonneg (by linarith)
  have hfac1 : ContinuousOn (fun u : ℝ => 120 + 4 * (137 * (2 * efT0 q u + 7)
      * Real.log ((q : ℝ) * (efT0 q u + 5)) + 1) / (Real.log (7 / 6) * (σb - σa)))
      (Set.Ici (3 : ℝ)) := by
    refine continuousOn_const.add (ContinuousOn.div_const (continuousOn_const.mul ?_) _)
    exact ((continuousOn_const.mul ((continuousOn_const.mul (cont_efT0 hq)).add
      continuousOn_const)).mul (cont_logQT hq 5 (by norm_num))).add continuousOn_const
  have hfac2 : ContinuousOn (fun u : ℝ =>
      Real.log (4 * (5 * (5 + efT0 q u) * Real.sqrt q * (1 + Real.log q)))) (Set.Ici (3 : ℝ)) := by
    refine cont_log_comp (continuousOn_const.mul (((continuousOn_const.mul
      (continuousOn_const.add (cont_efT0 hq))).mul continuousOn_const).mul continuousOn_const))
      (fun u hu => ne_of_gt ?_)
    have h1 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
    have h5 : (0 : ℝ) < 5 * (5 + efT0 q u) := by linarith
    have hs : (0 : ℝ) < Real.sqrt q := by linarith
    have hl : (0 : ℝ) < 1 + Real.log q := by linarith
    have := mul_pos (mul_pos h5 hs) hl
    linarith
  simp only [efShiftB]
  exact hfac1.mul hfac2

private lemma cont_efShiftBound {q : ℕ} (hq : 2 ≤ q) {σa σb : ℝ}
    (hσb1 : 0 < σb + 1) {φ : ℝ → ℝ} (hφ : ContinuousOn φ (Set.Ici (3 : ℝ)))
    (hφ3 : ∀ u ∈ Set.Ici (3 : ℝ), 3 ≤ φ u) :
    ContinuousOn (fun u : ℝ => efShiftBound q (efT0 q u) σa σb (φ u)) (Set.Ici (3 : ℝ)) := by
  have hlogφ : ContinuousOn (fun u : ℝ => Real.log (φ u)) (Set.Ici (3 : ℝ)) :=
    cont_log_comp hφ (fun u hu => ne_of_gt (by linarith [hφ3 u hu]))
  have hlogφ0 : ∀ u ∈ Set.Ici (3 : ℝ), Real.log (φ u) ≠ 0 := by
    intro u hu
    have h3 := hφ3 u hu
    have he : Real.exp 1 ≤ φ u :=
      le_trans (le_of_lt (lt_trans Real.exp_one_lt_d9 (by norm_num))) h3
    have : (1 : ℝ) ≤ Real.log (φ u) := (Real.le_log_iff_exp_le (by linarith)).mpr he
    linarith
  have hrow1 : ContinuousOn (fun u : ℝ => 2 * ((1 + 1 / Real.log (φ u)) - σa)
      * efShiftB q (efT0 q u) σa σb * (Real.exp 1 * φ u ^ (2 : ℕ)) / efT0 q u ^ 2)
      (Set.Ici (3 : ℝ)) := by
    refine ContinuousOn.div (((continuousOn_const.mul ((continuousOn_const.add
      (continuousOn_const.div hlogφ hlogφ0)).sub continuousOn_const)).mul
      (cont_efShiftB hq)).mul (continuousOn_const.mul (hφ.pow 2)))
      ((cont_efT0 hq).pow 2) (fun u hu => ?_)
    have h1 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
    positivity
  have hrow2 : ContinuousOn (fun u : ℝ => efShiftB q (efT0 q u) σa σb * φ u ^ (σb + 1)
      * (Real.pi / σa)) (Set.Ici (3 : ℝ)) :=
    ((cont_efShiftB hq).mul (hφ.rpow_const (fun u _ => Or.inr (by linarith)))).mul
      continuousOn_const
  have hrow3 : ContinuousOn (fun u : ℝ => (Real.log (φ u) + 1) * (Real.exp 1 * φ u ^ (2 : ℕ))
      * (2 / efT0 q u)) (Set.Ici (3 : ℝ)) := by
    refine ((hlogφ.add continuousOn_const).mul (continuousOn_const.mul (hφ.pow 2))).mul
      (continuousOn_const.div (cont_efT0 hq) (fun u hu => ?_))
    have h1 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
    linarith
  simp only [efShiftBound]
  exact continuousOn_const.mul ((hrow1.add hrow2).add hrow3)

/-- **The envelope is continuous on `[3,∞)`** — the last hypothesis
`logChiSum_add_mainTerm_norm_le` asks for, so parts (a)/(b) compose with the transfer without
any further side condition. -/
lemma continuousOn_efEnvelope {q : ℕ} (hq : 2 ≤ q) {β₀ bceil σa σb : ℝ} (m : ℕ)
    (hσb1 : 0 < σb + 1) :
    ContinuousOn (fun u : ℝ => efEnvelope q β₀ bceil m σa σb u) (Set.Ici (3 : ℝ)) := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hφ2 : ContinuousOn (fun u : ℝ => u + efH q u) (Set.Ici (3 : ℝ)) :=
    continuousOn_id.add (cont_efH hq)
  have hφ23 : ∀ u ∈ Set.Ici (3 : ℝ), (3 : ℝ) ≤ u + efH q u := by
    intro u hu
    have h3 : (3 : ℝ) ≤ u := hu
    linarith [efH_pos hq h3]
  have hA : ContinuousOn (fun u : ℝ => (efH q u + 1) * Real.log (u + efH q u))
      (Set.Ici (3 : ℝ)) :=
    ((cont_efH hq).add continuousOn_const).mul
      (cont_log_comp hφ2 (fun u hu => ne_of_gt (by linarith [hφ23 u hu])))
  have hB : ContinuousOn (fun u : ℝ => (efShiftBound q (efT0 q u) σa σb u
      + efShiftBound q (efT0 q u) σa σb (u + efH q u)) / efH q u) (Set.Ici (3 : ℝ)) :=
    ContinuousOn.div ((cont_efShiftBound hq hσb1 (continuousOn_id (α := ℝ)) (fun u hu => hu)).add
      (cont_efShiftBound hq hσb1 hφ2 hφ23)) (cont_efH hq)
      (fun u hu => ne_of_gt (efH_pos hq (show (3:ℝ) ≤ u from hu)))
  have hid : ContinuousOn (fun u : ℝ => u) (Set.Ici (3 : ℝ)) := continuousOn_id
  have hne0 : ∀ u ∈ Set.Ici (3 : ℝ), u ≠ 0 :=
    fun u hu => ne_of_gt (by linarith [show (3:ℝ) ≤ u from hu])
  have hrpow : ∀ p : ℝ, ContinuousOn (fun u : ℝ => u ^ p) (Set.Ici (3 : ℝ)) := fun p =>
    hid.rpow_const (fun u hu => Or.inl (hne0 u hu))
  have hC : ContinuousOn (fun u : ℝ => (m : ℝ) * (efH q u * u ^ (β₀ - 1))
      + efH q u * u ^ (bceil - 1)
        * (137 * (2 * efT0 q u + 5) * Real.log ((q : ℝ) * (efT0 q u + 4)))) (Set.Ici (3 : ℝ)) :=
    (continuousOn_const.mul ((cont_efH hq).mul (hrpow _))).add
      (((cont_efH hq).mul (hrpow _)).mul ((continuousOn_const.mul
        ((continuousOn_const.mul (cont_efT0 hq)).add continuousOn_const)).mul
        (cont_logQT hq 4 (by norm_num))))
  have hD : ContinuousOn (fun u : ℝ => u ^ bceil * (137 * Real.log ((q : ℝ) * (efT0 q u + 4))
      * (8 + 4 * Real.log (efT0 q u + 2)))) (Set.Ici (3 : ℝ)) := by
    refine (hrpow _).mul ((continuousOn_const.mul (cont_logQT hq 4 (by norm_num))).mul
      (continuousOn_const.add (continuousOn_const.mul ?_)))
    refine cont_log_comp ((cont_efT0 hq).add continuousOn_const) (fun u hu => ne_of_gt ?_)
    have h1 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
    linarith
  simp only [efEnvelope]
  exact ContinuousOn.div (((hA.add hB).add hC).add hD) hid hne0

/-! ### Nonnegativity, and the end-to-end composite -/

lemma efShiftB_nonneg {q : ℕ} {T₀ σa σb : ℝ} (hq : 2 ≤ q) (hT₀ : 2 ≤ T₀) (hσab : σa < σb) :
    0 ≤ efShiftB q T₀ σa σb := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hsq : (1 : ℝ) ≤ Real.sqrt q := by
    rw [show (1 : ℝ) = Real.sqrt 1 from (Real.sqrt_one).symm]
    exact Real.sqrt_le_sqrt (by linarith)
  have hlq : (0 : ℝ) ≤ Real.log q := Real.log_nonneg (by linarith)
  have hlog76 : (0 : ℝ) < Real.log (7 / 6) := Real.log_pos (by norm_num)
  have hlogQ : (0 : ℝ) ≤ Real.log ((q : ℝ) * (T₀ + 5)) := Real.log_nonneg (by nlinarith)
  have harg : (1 : ℝ) ≤ 4 * (5 * (5 + T₀) * Real.sqrt q * (1 + Real.log q)) := by
    have h1 : (35 : ℝ) ≤ 5 * (5 + T₀) := by linarith
    have h2 : (35 : ℝ) * 1 ≤ 5 * (5 + T₀) * Real.sqrt q :=
      mul_le_mul h1 hsq (by norm_num) (by linarith)
    have h3 : (35 : ℝ) * 1 ≤ 5 * (5 + T₀) * Real.sqrt q * (1 + Real.log q) :=
      mul_le_mul (by linarith) (by linarith) (by norm_num) (by linarith)
    linarith
  rw [efShiftB]
  refine mul_nonneg ?_ (Real.log_nonneg harg)
  have hnum : (0 : ℝ) ≤ 4 * (137 * (2 * T₀ + 7) * Real.log ((q : ℝ) * (T₀ + 5)) + 1) := by
    nlinarith
  have hden : (0 : ℝ) < Real.log (7 / 6) * (σb - σa) := by
    apply mul_pos hlog76; linarith
  have := div_nonneg hnum (le_of_lt hden)
  linarith

lemma efShiftBound_nonneg {q : ℕ} {T₀ σa σb x : ℝ} (hq : 2 ≤ q) (hT₀ : 2 ≤ T₀)
    (hσa : 0 < σa) (hσa1 : σa ≤ 1) (hσab : σa < σb) (hx : 3 ≤ x) :
    0 ≤ efShiftBound q T₀ σa σb x := by
  have hx0 : (0 : ℝ) < x := by linarith
  have hlogx : (0 : ℝ) < Real.log x := Real.log_pos (by linarith)
  have hBnn : 0 ≤ efShiftB q T₀ σa σb := efShiftB_nonneg hq hT₀ hσab
  have hT0pos : (0 : ℝ) < T₀ := by linarith
  have hex : (0 : ℝ) < Real.exp 1 * x ^ (2 : ℕ) := by positivity
  have hc : (0 : ℝ) ≤ (1 + 1 / Real.log x) - σa := by
    have : (0 : ℝ) < 1 / Real.log x := by positivity
    linarith
  rw [efShiftBound]
  refine mul_nonneg (by positivity) (add_nonneg (add_nonneg ?_ ?_) ?_)
  · exact div_nonneg (mul_nonneg (mul_nonneg (by linarith) hBnn) (le_of_lt hex)) (by positivity)
  · exact mul_nonneg (mul_nonneg hBnn (le_of_lt (Real.rpow_pos_of_pos hx0 _)))
      (by positivity [Real.pi_pos])
  · exact mul_nonneg (mul_nonneg (by linarith) (le_of_lt hex)) (by positivity)

lemma efEnvelope_nonneg {q : ℕ} {β₀ bceil σa σb u : ℝ} {m : ℕ} (hq : 2 ≤ q) (hu : 3 ≤ u)
    (hσa : 0 < σa) (hσa1 : σa ≤ 1) (hσab : σa < σb) :
    0 ≤ efEnvelope q β₀ bceil m σa σb u := by
  have hq2 : (2 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  have hu0 : (0 : ℝ) < u := by linarith
  have hT0 : (2 : ℝ) ≤ efT0 q u := two_le_efT0 hq hu
  have hHpos : 0 < efH q u := efH_pos hq hu
  have huh : (3 : ℝ) ≤ u + efH q u := by linarith
  have hlogQ4 : (0 : ℝ) ≤ Real.log ((q : ℝ) * (efT0 q u + 4)) := Real.log_nonneg (by nlinarith)
  have hlogT2 : (0 : ℝ) ≤ Real.log (efT0 q u + 2) := Real.log_nonneg (by linarith)
  have hrp1 : (0 : ℝ) < u ^ (β₀ - 1) := Real.rpow_pos_of_pos hu0 _
  have hrp2 : (0 : ℝ) < u ^ (bceil - 1) := Real.rpow_pos_of_pos hu0 _
  have hrp3 : (0 : ℝ) < u ^ bceil := Real.rpow_pos_of_pos hu0 _
  rw [efEnvelope]
  refine div_nonneg (add_nonneg (add_nonneg (add_nonneg ?_ ?_) ?_) ?_) (by linarith)
  · exact mul_nonneg (by linarith) (Real.log_nonneg (by linarith))
  · exact div_nonneg (add_nonneg (efShiftBound_nonneg hq hT0 hσa hσa1 hσab hu)
      (efShiftBound_nonneg hq hT0 hσa hσa1 hσab huh)) (le_of_lt hHpos)
  · refine add_nonneg (by positivity) (mul_nonneg (by positivity) ?_)
    have : (0 : ℝ) ≤ 137 * (2 * efT0 q u + 5) := by linarith
    exact mul_nonneg this hlogQ4
  · refine mul_nonneg (le_of_lt hrp3) (mul_nonneg (mul_nonneg (by norm_num) hlogQ4) ?_)
    linarith

/-- **THE (4.12) COMPOSITE AT THE DESIGN PARAMETERS (N4b W2b, (a)+(b) composed).**  Everything
of W2 in one statement: for `3 ≤ X ≤ Y`,

    ‖∑_{X<n≤Y} χ(n)Λ(n)/(n log n) + m·∫_X^Y v^{β₀−2}/log v dv‖
      ≤ G X/log X + G Y/log Y + 2·∫_X^Y G t/(t log t) dt,  G = efEnvelope …,

uniformly in `Y`, at the freeze's own parameters `T₀(u) = (log qu + 2)^6`, `h(u) = u/√T₀(u)`, with
`m = zeroMult χ β₀` explicit and ONE named ceiling binder `hceil` (discharged in §6 by the
Range-A repulsion and the Range-B zero-free region).  `G` is the closed-form envelope of §7; the
numeric closure of the six ledger rows — which is what turns the right-hand side into
`K·(log X)^{−1/2}` — is the residue recorded in `docs/blueprints/flags.md`. -/
theorem logChiSum_composite_of_ceiling {q : ℕ} [NeZero q] (χ : DirichletCharacter ℂ q)
    (hχ : χ.IsPrimitive) (hq : 2 ≤ q) {β₀ bceil X Y σa σb : ℝ}
    (hX : 3 ≤ X) (hXY : X ≤ Y) (hσa : 9 / 10 ≤ σa) (hσab : σa < σb) (hσb : σb < 1)
    (hβ₀0 : 0 < β₀) (hβ₀1 : β₀ ≤ 1) (hσbβ₀ : σb ≤ β₀) (hβ₀zero : LFunction χ (β₀ : ℂ) = 0)
    (hceil : ∀ t ∈ Set.Icc X Y, ∀ ρ : ℂ, LFunction χ ρ = 0 → ρ ≠ (β₀ : ℂ) → 9 / 10 ≤ ρ.re →
      ρ.re ≤ 1 → |ρ.im| ≤ efT0 q t + 1 → ρ.re ≤ bceil) :
    ‖logChiSum χ X Y
        + (zeroMult χ (β₀ : ℂ) : ℂ) * ((∫ t in X..Y, t ^ (β₀ - 2) / Real.log t : ℝ) : ℂ)‖
      ≤ efEnvelope q β₀ bceil (zeroMult χ (β₀ : ℂ)) σa σb X / Real.log X
        + efEnvelope q β₀ bceil (zeroMult χ (β₀ : ℂ)) σa σb Y / Real.log Y
        + 2 * ∫ t in X..Y,
            efEnvelope q β₀ bceil (zeroMult χ (β₀ : ℂ)) σa σb t / (t * Real.log t) := by
  have hsub : Set.Icc X Y ⊆ Set.Ici (3 : ℝ) := fun t ht => le_trans hX ht.1
  refine logChiSum_add_mainTerm_norm_le χ hβ₀0 (zeroMult χ (β₀ : ℂ)) hX hXY
    ((continuousOn_efEnvelope hq (β₀ := β₀) (bceil := bceil) _ (by linarith)).mono hsub)
    (fun t ht => efEnvelope_nonneg hq (le_trans hX ht.1) (by linarith) (by linarith) hσab)
    (fun t ht => psiDefect_norm_le_envelope χ hχ hq (le_trans hX ht.1) hσa hσab hσb hβ₀1
      hσbβ₀ hβ₀zero (hceil t ht))

end Salt.HB
