/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
import Mathlib
import Salt.Chen.SuperProfile

/-!
# SS3a — the concrete super-solution profile: definitions + budget integrals

Design: `docs/blueprints/flags.md`, `2026-07-13 SS2`/`SS3`.  Part 1 of the 3-way SS3
transcription split.  This file records the **exact-rational-certified** piecewise-linear
profile `(Ebar, Obar)` (regenerated by `scripts/ss2_profile.py`) as honest Lean functions,
proves the definitional interface the domination panels (SS3b/SS3c) consume, and discharges the
two `∫`-budgets that `SuperSolution.massSum_le_A2_of_superSolution` /
`massOSum_le_A1_of_superSolution` require (`hEbound`/`hObound`).

## The profile

Shared grid spacing `h = 1/20`.  `Ebar` is PL on the 200 panels over `[2,12]`, `Obar` PL on
the 220 panels over `[1,12]`; beyond `W = 12` both carry the power tail `K/v³`, `K = 1/10000`.
Knots are stored as **natural-number numerators over `10⁷`** (`ebarNumList`/`obarNumList`, exact
by construction), so nonnegativity is structural and the trapezoid budget reduces to a `ℕ`-sum.

* `EbarKnots i = (ebarNumList.getD i 0)/10⁷`, `ObarKnots i = (obarNumList.getD i 0)/10⁷`.
* `Ebar v = 0` for `v < 2`, `= plVal EbarKnots 2 ⌊(v−2)·20⌋₊ v` on `[2,12)`, `= K/v³` for `v ≥ 12`.
* `Obar w = 0` for `w < 1`, `= plVal ObarKnots 1 ⌊(w−1)·20⌋₊ w` on `[1,12)`, `= K/w³` for `w ≥ 12`.

## Seam convention (load-bearing for SS3b/SS3c)

At the single point `v = 12` the tail branch wins (`Ebar 12 = K/12³`, NOT the last knot value).
Hence `*_tail_eq` holds on the **closed** `[12,∞)` (`∀ v ≥ 12`), and `*_panel_eq` holds on the
**half-open** panel `Ico (left + i/20) (left + (i+1) / 20)`.  The 200/220 half-open panels tile
`[2,12)`/`[1,12)` and the tail covers `[12,∞)` with no overlap — the clean pointwise cover the
domination panels split on.

## The interface (frozen — SS3b/SS3c consume these)

`EbarKnots`/`ObarKnots`, `Ebar`/`Obar`, `Ebar_nonneg`/`Obar_nonneg`,
`Ebar_intervalIntegrable`/`Obar_intervalIntegrable`, `Ebar_panel_eq`/`Obar_panel_eq` (Ico form),
`Ebar_tail_eq`/`Obar_tail_eq` (`∀ v ≥ 12`), and the two budgets `Ebar_integral_le`
(`∫_2^b ≤ 43/75`, `∀ b ≥ 2`) / `Obar_integral_le` (`∫_3^b ≤ 11/125`, `∀ b ≥ 3`).

Certificate (exact rationals, from `scripts/ss2_profile.py`):
`∫_2^12 Ebar = 112618127/200000000`, `∫_3^12 Obar = 34739321/400000000`; with the tail
`K/(2·12²) = 1/2880000` these give `∫_2^∞ Ebar = 126695471/225000000 ≤ 43/75` and
`∫_3^∞ Obar = 312655139/3600000000 ≤ 11/125`.
-/

open Finset MeasureTheory intervalIntegral Set

namespace Salt.Chen

-- `maxRecDepth` is raised only for the `by decide` uniform knot bound (`*Num_le`), which recurses
-- once per entry over the 201/221-element numerator lists.  No `maxHeartbeats` bump is needed.
set_option maxRecDepth 4000

/-! ## Shared piecewise-linear interpolation atom -/

/-- Linear interpolation on panel `i` (width `1/20`, left edge `left + i/20`) of a knot table
`c`, evaluated at `x`: `c i + (c (i+1) − c i)·(x − (left + i/20))·20`. -/
noncomputable def plVal (c : ℕ → ℚ) (left : ℝ) (i : ℕ) (x : ℝ) : ℝ :=
  (c i : ℝ) + ((c (i+1) : ℝ) - (c i : ℝ)) * (x - (left + (i : ℝ) / 20)) * 20


/-! ## The even profile `Ebar` -/

def ebarNumList : List ℕ :=
  [10007043, 9158801, 8389475, 7690212, 7053385, 6472381, 5941449, 5455558, 5010292, 4601766,
   4226538, 3881561, 3564122, 3271799, 3002427, 2754065, 2524966, 2313556, 2118415, 1938256,
   1771915, 1618331, 1476541, 1345668, 1224908, 1113528, 1010856, 916278, 829227, 749182,
   675666, 608236, 546485, 490037, 438544, 391682, 349155, 310684, 276011, 244898,
   217122, 192429, 170512, 151055, 133777, 118432, 104804, 92700, 81952, 72409,
   63938, 56421, 49753, 43841, 38601, 33961, 29853, 26220, 23008, 20172,
   17669, 15463, 13519, 11809, 10306, 8986, 7828, 6814, 5926, 5150,
   4473, 3882, 3367, 2918, 2528, 2190, 1895, 1640, 1419, 1227,
   1060, 916, 791, 683, 589, 508, 438, 377, 325, 280,
   241, 207, 178, 153, 132, 113, 97, 83, 72, 62,
   53, 45, 39, 34, 29, 25, 22, 19, 16, 14,
   12, 11, 9, 8, 7, 6, 6, 5, 5, 4,
   4, 3, 3, 3, 3, 3, 2, 2, 2, 2,
   2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1]

/-- Knot numerator lookup (natural, zero past the table). -/
def EbarNum (i : ℕ) : ℕ := ebarNumList.getD i 0

/-- Knot value `= numerator / 10⁷` (nonneg by construction). -/
noncomputable def EbarKnots (i : ℕ) : ℚ := (EbarNum i : ℚ) / 10000000

theorem EbarKnots_nonneg (i : ℕ) : (0 : ℝ) ≤ (EbarKnots i : ℝ) := by
  unfold EbarKnots; push_cast; positivity

theorem EbarNum_le (i : ℕ) : EbarNum i ≤ 20000000 := by
  have hall : ∀ x ∈ ebarNumList, x ≤ 20000000 := by decide
  unfold EbarNum
  rcases lt_or_ge i ebarNumList.length with h | h
  · rw [List.getD_eq_getElem _ _ h]; exact hall _ (List.getElem_mem h)
  · rw [List.getD_eq_default (hn := h)]; exact Nat.zero_le _

theorem EbarKnots_le (i : ℕ) : (EbarKnots i : ℝ) ≤ 2 := by
  have h : (EbarNum i : ℝ) ≤ 20000000 := by exact_mod_cast EbarNum_le i
  unfold EbarKnots; push_cast; rw [div_le_iff₀ (by norm_num)]; linarith

/-- The even PL profile: `0` below `2`, PL on `[2,12)`, power tail `K/v³` from `12`. -/
noncomputable def Ebar (v : ℝ) : ℝ :=
  if v < 2 then 0
  else if 12 ≤ v then (1/10000) / v^3
  else plVal EbarKnots 2 (⌊(v - 2) * 20⌋).toNat v

theorem Ebar_tail_eq (v : ℝ) (hv : 12 ≤ v) : Ebar v = (1/10000) / v^3 := by
  unfold Ebar; rw [if_neg (by linarith), if_pos hv]

/-- **Panel equation (half-open).**  On `Ico (2 + i/20) (2 + (i+1) / 20)`, `Ebar` is the
linear interpolation between knots `i` and `i+1`. -/
theorem Ebar_panel_eq (i : ℕ) (hi : i < 200) (v : ℝ)
    (hv : v ∈ Set.Ico (2 + (i : ℝ) / 20) (2 + ((i : ℝ) + 1) / 20)) :
    Ebar v = (EbarKnots i : ℝ)
      + ((EbarKnots (i+1) : ℝ) - (EbarKnots i : ℝ)) * (v - (2 + (i : ℝ) / 20)) * 20 := by
  obtain ⟨hvl, hvr⟩ := hv
  have hinn : (0 : ℝ) ≤ (i : ℝ) / 20 := by positivity
  have hi2 : (2 : ℝ) ≤ v := by linarith
  have hile : (i : ℝ) + 1 ≤ 200 := by exact_mod_cast (by omega : i + 1 ≤ 200)
  have hlt12 : v < 12 := by
    have h10 : ((i : ℝ) + 1) / 20 ≤ 10 := by rw [div_le_iff₀ (by norm_num)]; linarith
    linarith
  have hfloor : ⌊(v - 2) * 20⌋ = (i : ℤ) := by
    rw [Int.floor_eq_iff]
    refine ⟨by push_cast; nlinarith [hvl], by push_cast; nlinarith [hvr]⟩
  unfold Ebar
  rw [if_neg (by linarith), if_neg (by linarith), hfloor, Int.toNat_natCast]
  unfold plVal; ring

theorem Ebar_nonneg (v : ℝ) : 0 ≤ Ebar v := by
  unfold Ebar
  split_ifs with h1 h2
  · exact le_refl 0
  · have hv : (0 : ℝ) < v := by linarith
    positivity
  · rw [not_lt] at h1; rw [not_le] at h2
    set n := ⌊(v - 2) * 20⌋ with hn
    have hnn : (0 : ℤ) ≤ n := by rw [hn]; apply Int.le_floor.2; push_cast; nlinarith [h1]
    have hcast : (n.toNat : ℤ) = n := Int.toNat_of_nonneg hnn
    have htn : (n.toNat : ℝ) = (n : ℝ) := by exact_mod_cast hcast
    have hfl := Int.floor_le ((v - 2) * 20)
    have hfu := Int.lt_floor_add_one ((v - 2) * 20)
    rw [← hn] at hfl hfu
    set i := n.toNat with hi
    unfold plVal
    have hfrac0 : (0 : ℝ) ≤ (v - (2 + (i : ℝ) / 20)) * 20 := by rw [htn]; nlinarith [hfl]
    have hfrac1 : (v - (2 + (i : ℝ) / 20)) * 20 ≤ 1 := by rw [htn]; nlinarith [hfu]
    have hc0 := EbarKnots_nonneg i
    have hc1 := EbarKnots_nonneg (i+1)
    nlinarith [hc0, hc1, hfrac0, hfrac1]

theorem Ebar_bdd (v : ℝ) : |Ebar v| ≤ 2 := by
  rw [abs_le]
  refine ⟨by linarith [Ebar_nonneg v], ?_⟩
  unfold Ebar
  split_ifs with h1 h2
  · norm_num
  · have hv : (0 : ℝ) < v := by linarith
    have h123 : (12 : ℝ)^3 ≤ v^3 := by gcongr
    have hle : (1/10000 : ℝ)/v^3 ≤ 2 := by rw [div_le_iff₀ (by positivity)]; nlinarith [h123]
    linarith
  · rw [not_lt] at h1; rw [not_le] at h2
    set n := ⌊(v - 2) * 20⌋ with hn
    have hnn : (0 : ℤ) ≤ n := by rw [hn]; apply Int.le_floor.2; push_cast; nlinarith [h1]
    have hcast : (n.toNat : ℤ) = n := Int.toNat_of_nonneg hnn
    have htn : (n.toNat : ℝ) = (n : ℝ) := by exact_mod_cast hcast
    have hfl := Int.floor_le ((v - 2) * 20)
    have hfu := Int.lt_floor_add_one ((v - 2) * 20)
    rw [← hn] at hfl hfu
    set i := n.toNat with hi
    unfold plVal
    have hfrac0 : (0 : ℝ) ≤ (v - (2 + (i : ℝ) / 20)) * 20 := by rw [htn]; nlinarith [hfl]
    have hfrac1 : (v - (2 + (i : ℝ) / 20)) * 20 ≤ 1 := by rw [htn]; nlinarith [hfu]
    have hc0 := EbarKnots_le i
    have hc1 := EbarKnots_le (i+1)
    have hc0n := EbarKnots_nonneg i
    have hc1n := EbarKnots_nonneg (i+1)
    nlinarith [hc0, hc1, hc0n, hc1n, hfrac0, hfrac1]

theorem Ebar_measurable : Measurable Ebar := by
  have haff : Measurable (fun v : ℝ => (v - 2) * 20) := by fun_prop
  have hidx : Measurable (fun v : ℝ => (⌊(v - 2) * 20⌋).toNat) :=
    (measurable_from_top (f := Int.toNat)).comp (Int.measurable_floor.comp haff)
  have ha : Measurable (fun v : ℝ => (EbarKnots (⌊(v - 2) * 20⌋).toNat : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (EbarKnots n : ℝ))).comp hidx
  have hb : Measurable (fun v : ℝ => (EbarKnots ((⌊(v - 2) * 20⌋).toNat + 1) : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (EbarKnots (n+1) : ℝ))).comp hidx
  have hc : Measurable (fun v : ℝ => ((⌊(v - 2) * 20⌋).toNat : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (n : ℝ))).comp hidx
  unfold Ebar
  refine Measurable.ite (measurableSet_lt measurable_id measurable_const) measurable_const ?_
  refine Measurable.ite (measurableSet_le measurable_const measurable_id) (by fun_prop) ?_
  unfold plVal
  exact ha.add
    (((hb.sub ha).mul
      (measurable_id.sub (measurable_const.add (hc.div measurable_const)))).mul measurable_const)

/-- **Interval integrability** (bounded + measurable on every finite interval). -/
theorem Ebar_intervalIntegrable (a b : ℝ) : IntervalIntegrable Ebar volume a b := by
  rw [intervalIntegrable_iff]
  refine Measure.integrableOn_of_bounded (measure_Ioc_lt_top).ne
    Ebar_measurable.aestronglyMeasurable (M := 2) (ae_of_all _ (fun x => ?_))
  rw [Real.norm_eq_abs]
  exact Ebar_bdd x

/-- **Exact panel integral** = trapezoid `(c i + c (i+1)) / 40`. -/
theorem Ebar_panel_integral (i : ℕ) (hi : i < 200) :
    (∫ v in (2 + (i : ℝ) / 20)..(2 + ((i : ℝ) + 1) / 20), Ebar v)
      = ((EbarKnots i : ℝ) + (EbarKnots (i+1) : ℝ)) / 40 := by
  have hLR : (2 + (i : ℝ) / 20) ≤ (2 + ((i : ℝ) + 1) / 20) := by
    have : (i : ℝ) / 20 ≤ ((i : ℝ) + 1) / 20 := by gcongr; linarith
    linarith
  set ci := (EbarKnots i : ℝ) with hci
  set cj := (EbarKnots (i+1) : ℝ) with hcj
  have hcong : ∀ᵐ x ∂volume, x ∈ Set.uIoc (2+(i : ℝ) / 20) (2+((i : ℝ) + 1) / 20) →
      Ebar x = (ci - (cj-ci) * 20*(2+(i : ℝ) / 20)) + ((cj-ci) * 20)*x := by
    filter_upwards [compl_mem_ae_iff.2 (measure_singleton (2 + ((i : ℝ) + 1) / 20))] with x hx hmem
    rw [Set.uIoc_of_le hLR] at hmem
    have hxR : x < 2 + ((i : ℝ) + 1) / 20 := lt_of_le_of_ne hmem.2 (by simpa using hx)
    rw [Ebar_panel_eq i hi x ⟨hmem.1.le, hxR⟩]; ring
  rw [intervalIntegral.integral_congr_ae hcong, integral_line]
  field_simp; ring

/-- **Cumulative PL integral** over `[2, 2 + n/20]` = trapezoid partial sum. -/
theorem Ebar_cumint (n : ℕ) (hn : n ≤ 200) :
    (∫ v in (2 : ℝ)..(2 + (n : ℝ) / 20), Ebar v)
      = ∑ i ∈ Finset.range n, ((EbarKnots i : ℝ) + (EbarKnots (i+1) : ℝ)) / 40 := by
  induction n with
  | zero => simp
  | succ m ih =>
    have hm : m ≤ 200 := by omega
    have hmlt : m < 200 := by omega
    have hcast : ((m : ℝ) + 1) = ((m+1 : ℕ) : ℝ) := by push_cast; ring
    rw [Finset.sum_range_succ, ← ih hm, ← Ebar_panel_integral m hmlt,
        intervalIntegral.integral_add_adjacent_intervals
          (Ebar_intervalIntegrable 2 (2 + (m : ℝ) / 20))
          (Ebar_intervalIntegrable (2 + (m : ℝ) / 20) (2 + ((m : ℝ) + 1) / 20)), hcast]

theorem Ebar_sum_eq :
    ∑ i ∈ Finset.range 200, ((EbarKnots i : ℝ) + (EbarKnots (i+1) : ℝ)) / 40
      = 112618127/200000000 := by
  have hnat : (∑ i ∈ Finset.range 200, (EbarNum i + EbarNum (i+1))) = 225236254 := by
    simp only [Finset.sum_range_succ, Finset.sum_range_zero, EbarNum, ebarNumList,
      List.getD_cons_zero, List.getD_cons_succ]
  have hstep : ∀ i ∈ Finset.range 200,
      ((EbarKnots i : ℝ) + (EbarKnots (i+1) : ℝ)) / 40
        = ((EbarNum i : ℝ) + (EbarNum (i+1) : ℝ)) / 400000000 := by
    intro i _; unfold EbarKnots; push_cast; ring
  rw [Finset.sum_congr rfl hstep, ← Finset.sum_div,
      show (∑ i ∈ Finset.range 200, ((EbarNum i : ℝ)+(EbarNum (i+1) : ℝ)))
        = ((∑ i ∈ Finset.range 200, (EbarNum i + EbarNum (i+1)) : ℕ) : ℝ) by push_cast; ring,
      hnat]
  norm_num

theorem Ebar_int_2_12 : (∫ v in (2 : ℝ)..12, Ebar v) = 112618127/200000000 := by
  have h := Ebar_cumint 200 (le_refl 200)
  rw [Ebar_sum_eq] at h
  rw [show (12 : ℝ) = 2 + ((200 : ℕ) : ℝ) / 20 by norm_num]
  exact h

/-- **Even budget.**  `∫_2^b Ebar ≤ 43/75` for every `b ≥ 2` (the `hEbound` SS1 consumes). -/
theorem Ebar_integral_le : ∀ b, 2 ≤ b → (∫ v in (2 : ℝ)..b, Ebar v) ≤ 43/75 := by
  intro b hb
  have hle : (112618127/200000000 : ℝ) ≤ 43/75 := by norm_num
  rcases le_or_gt b 12 with hb12 | hb12
  · have hsplit : (∫ v in (2 : ℝ)..12, Ebar v)
        = (∫ v in (2 : ℝ)..b, Ebar v) + ∫ v in b..12, Ebar v :=
      (intervalIntegral.integral_add_adjacent_intervals
        (Ebar_intervalIntegrable 2 b) (Ebar_intervalIntegrable b 12)).symm
    have htail0 : 0 ≤ ∫ v in b..12, Ebar v :=
      intervalIntegral.integral_nonneg hb12 (fun x _ => Ebar_nonneg x)
    have h212 := Ebar_int_2_12
    linarith
  · have hsplit : (∫ v in (2 : ℝ)..b, Ebar v)
        = (∫ v in (2 : ℝ)..12, Ebar v) + ∫ v in (12 : ℝ)..b, Ebar v :=
      (intervalIntegral.integral_add_adjacent_intervals
        (Ebar_intervalIntegrable 2 12) (Ebar_intervalIntegrable 12 b)).symm
    have htaileq : (∫ v in (12 : ℝ)..b, Ebar v) = ∫ v in (12 : ℝ)..b, (1/10000)/v^3 := by
      apply intervalIntegral.integral_congr
      intro x hx; rw [Set.uIcc_of_le hb12.le] at hx; exact Ebar_tail_eq x hx.1
    have htailbd : (∫ v in (12 : ℝ)..b, (1/10000 : ℝ)/v^3) ≤ (1/10000)/(2*12^2) :=
      tail_integral_le (by norm_num) (by norm_num) hb12.le
    have h212 := Ebar_int_2_12
    have hbudget : (112618127/200000000 : ℝ) + (1/10000)/(2*12^2) ≤ 43/75 := by norm_num
    linarith

/-! ## The even profile `Obar` -/

def obarNumList : List ℕ :=
  [5630910, 5362772, 5119009, 4896444, 4692425, 4504728, 4331470, 4171045, 4022079, 3883387,
   3753940, 3632846, 3519319, 3412673, 3312300, 3217663, 3128284, 3043736, 2963637, 2887647,
   2815455, 2746786, 2681386, 2619028, 2559505, 2502627, 2448222, 2396132, 2346213, 2298331,
   2252364, 2208200, 2165735, 2124872, 2085523, 2047604, 2011040, 1975758, 1941694, 1908783,
   1876970, 1689103, 1520341, 1368592, 1232024, 1109025, 998178, 898227, 808063, 726700,
   653259, 586959, 527100, 473059, 424272, 380239, 340505, 304664, 272348, 243226,
   216997, 193390, 172161, 153085, 135962, 120607, 106853, 94550, 83557, 73751,
   65016, 57247, 50349, 44235, 38825, 34047, 29834, 26125, 22865, 20003,
   17493, 15292, 13363, 11673, 10191, 8893, 7756, 6761, 5889, 5127,
   4461, 3879, 3370, 2926, 2539, 2201, 1907, 1651, 1429, 1235,
   1067, 922, 795, 686, 591, 509, 439, 377, 325, 279,
   240, 206, 177, 152, 131, 113, 97, 83, 71, 61,
   53, 45, 39, 34, 29, 25, 22, 19, 16, 14,
   12, 11, 9, 8, 7, 6, 6, 5, 5, 4,
   4, 3, 3, 3, 3, 3, 2, 2, 2, 2,
   2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1]

/-- Knot numerator lookup (natural, zero past the table). -/
def ObarNum (i : ℕ) : ℕ := obarNumList.getD i 0

/-- Knot value `= numerator / 10⁷` (nonneg by construction). -/
noncomputable def ObarKnots (i : ℕ) : ℚ := (ObarNum i : ℚ) / 10000000

theorem ObarKnots_nonneg (i : ℕ) : (0 : ℝ) ≤ (ObarKnots i : ℝ) := by
  unfold ObarKnots; push_cast; positivity

theorem ObarNum_le (i : ℕ) : ObarNum i ≤ 20000000 := by
  have hall : ∀ x ∈ obarNumList, x ≤ 20000000 := by decide
  unfold ObarNum
  rcases lt_or_ge i obarNumList.length with h | h
  · rw [List.getD_eq_getElem _ _ h]; exact hall _ (List.getElem_mem h)
  · rw [List.getD_eq_default (hn := h)]; exact Nat.zero_le _

theorem ObarKnots_le (i : ℕ) : (ObarKnots i : ℝ) ≤ 2 := by
  have h : (ObarNum i : ℝ) ≤ 20000000 := by exact_mod_cast ObarNum_le i
  unfold ObarKnots; push_cast; rw [div_le_iff₀ (by norm_num)]; linarith

/-- The even PL profile: `0` below `1`, PL on `[1,12)`, power tail `K/v³` from `12`. -/
noncomputable def Obar (v : ℝ) : ℝ :=
  if v < 1 then 0
  else if 12 ≤ v then (1/10000) / v^3
  else plVal ObarKnots 1 (⌊(v - 1) * 20⌋).toNat v

theorem Obar_tail_eq (v : ℝ) (hv : 12 ≤ v) : Obar v = (1/10000) / v^3 := by
  unfold Obar; rw [if_neg (by linarith), if_pos hv]

/-- **Panel equation (half-open).**  On `Ico (1 + i/20) (1 + (i+1) / 20)`, `Obar` is the
linear interpolation between knots `i` and `i+1`. -/
theorem Obar_panel_eq (i : ℕ) (hi : i < 220) (v : ℝ)
    (hv : v ∈ Set.Ico (1 + (i : ℝ) / 20) (1 + ((i : ℝ) + 1) / 20)) :
    Obar v = (ObarKnots i : ℝ)
      + ((ObarKnots (i+1) : ℝ) - (ObarKnots i : ℝ)) * (v - (1 + (i : ℝ) / 20)) * 20 := by
  obtain ⟨hvl, hvr⟩ := hv
  have hinn : (0 : ℝ) ≤ (i : ℝ) / 20 := by positivity
  have hi2 : (1 : ℝ) ≤ v := by linarith
  have hile : (i : ℝ) + 1 ≤ 220 := by exact_mod_cast (by omega : i + 1 ≤ 220)
  have hlt12 : v < 12 := by
    have h10 : ((i : ℝ) + 1) / 20 ≤ 11 := by rw [div_le_iff₀ (by norm_num)]; linarith
    linarith
  have hfloor : ⌊(v - 1) * 20⌋ = (i : ℤ) := by
    rw [Int.floor_eq_iff]
    refine ⟨by push_cast; nlinarith [hvl], by push_cast; nlinarith [hvr]⟩
  unfold Obar
  rw [if_neg (by linarith), if_neg (by linarith), hfloor, Int.toNat_natCast]
  unfold plVal; ring

theorem Obar_nonneg (v : ℝ) : 0 ≤ Obar v := by
  unfold Obar
  split_ifs with h1 h2
  · exact le_refl 0
  · have hv : (0 : ℝ) < v := by linarith
    positivity
  · rw [not_lt] at h1; rw [not_le] at h2
    set n := ⌊(v - 1) * 20⌋ with hn
    have hnn : (0 : ℤ) ≤ n := by rw [hn]; apply Int.le_floor.2; push_cast; nlinarith [h1]
    have hcast : (n.toNat : ℤ) = n := Int.toNat_of_nonneg hnn
    have htn : (n.toNat : ℝ) = (n : ℝ) := by exact_mod_cast hcast
    have hfl := Int.floor_le ((v - 1) * 20)
    have hfu := Int.lt_floor_add_one ((v - 1) * 20)
    rw [← hn] at hfl hfu
    set i := n.toNat with hi
    unfold plVal
    have hfrac0 : (0 : ℝ) ≤ (v - (1 + (i : ℝ) / 20)) * 20 := by rw [htn]; nlinarith [hfl]
    have hfrac1 : (v - (1 + (i : ℝ) / 20)) * 20 ≤ 1 := by rw [htn]; nlinarith [hfu]
    have hc0 := ObarKnots_nonneg i
    have hc1 := ObarKnots_nonneg (i+1)
    nlinarith [hc0, hc1, hfrac0, hfrac1]

theorem Obar_bdd (v : ℝ) : |Obar v| ≤ 2 := by
  rw [abs_le]
  refine ⟨by linarith [Obar_nonneg v], ?_⟩
  unfold Obar
  split_ifs with h1 h2
  · norm_num
  · have hv : (0 : ℝ) < v := by linarith
    have h123 : (12 : ℝ)^3 ≤ v^3 := by gcongr
    have hle : (1/10000 : ℝ)/v^3 ≤ 2 := by rw [div_le_iff₀ (by positivity)]; nlinarith [h123]
    linarith
  · rw [not_lt] at h1; rw [not_le] at h2
    set n := ⌊(v - 1) * 20⌋ with hn
    have hnn : (0 : ℤ) ≤ n := by rw [hn]; apply Int.le_floor.2; push_cast; nlinarith [h1]
    have hcast : (n.toNat : ℤ) = n := Int.toNat_of_nonneg hnn
    have htn : (n.toNat : ℝ) = (n : ℝ) := by exact_mod_cast hcast
    have hfl := Int.floor_le ((v - 1) * 20)
    have hfu := Int.lt_floor_add_one ((v - 1) * 20)
    rw [← hn] at hfl hfu
    set i := n.toNat with hi
    unfold plVal
    have hfrac0 : (0 : ℝ) ≤ (v - (1 + (i : ℝ) / 20)) * 20 := by rw [htn]; nlinarith [hfl]
    have hfrac1 : (v - (1 + (i : ℝ) / 20)) * 20 ≤ 1 := by rw [htn]; nlinarith [hfu]
    have hc0 := ObarKnots_le i
    have hc1 := ObarKnots_le (i+1)
    have hc0n := ObarKnots_nonneg i
    have hc1n := ObarKnots_nonneg (i+1)
    nlinarith [hc0, hc1, hc0n, hc1n, hfrac0, hfrac1]

theorem Obar_measurable : Measurable Obar := by
  have haff : Measurable (fun v : ℝ => (v - 1) * 20) := by fun_prop
  have hidx : Measurable (fun v : ℝ => (⌊(v - 1) * 20⌋).toNat) :=
    (measurable_from_top (f := Int.toNat)).comp (Int.measurable_floor.comp haff)
  have ha : Measurable (fun v : ℝ => (ObarKnots (⌊(v - 1) * 20⌋).toNat : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (ObarKnots n : ℝ))).comp hidx
  have hb : Measurable (fun v : ℝ => (ObarKnots ((⌊(v - 1) * 20⌋).toNat + 1) : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (ObarKnots (n+1) : ℝ))).comp hidx
  have hc : Measurable (fun v : ℝ => ((⌊(v - 1) * 20⌋).toNat : ℝ)) :=
    (measurable_from_top (f := fun n : ℕ => (n : ℝ))).comp hidx
  unfold Obar
  refine Measurable.ite (measurableSet_lt measurable_id measurable_const) measurable_const ?_
  refine Measurable.ite (measurableSet_le measurable_const measurable_id) (by fun_prop) ?_
  unfold plVal
  exact ha.add
    (((hb.sub ha).mul
      (measurable_id.sub (measurable_const.add (hc.div measurable_const)))).mul measurable_const)

/-- **Interval integrability** (bounded + measurable on every finite interval). -/
theorem Obar_intervalIntegrable (a b : ℝ) : IntervalIntegrable Obar volume a b := by
  rw [intervalIntegrable_iff]
  refine Measure.integrableOn_of_bounded (measure_Ioc_lt_top).ne
    Obar_measurable.aestronglyMeasurable (M := 2) (ae_of_all _ (fun x => ?_))
  rw [Real.norm_eq_abs]
  exact Obar_bdd x

/-- **Exact panel integral** = trapezoid `(c i + c (i+1)) / 40`. -/
theorem Obar_panel_integral (i : ℕ) (hi : i < 220) :
    (∫ v in (1 + (i : ℝ) / 20)..(1 + ((i : ℝ) + 1) / 20), Obar v)
      = ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40 := by
  have hLR : (1 + (i : ℝ) / 20) ≤ (1 + ((i : ℝ) + 1) / 20) := by
    have : (i : ℝ) / 20 ≤ ((i : ℝ) + 1) / 20 := by gcongr; linarith
    linarith
  set ci := (ObarKnots i : ℝ) with hci
  set cj := (ObarKnots (i+1) : ℝ) with hcj
  have hcong : ∀ᵐ x ∂volume, x ∈ Set.uIoc (1+(i : ℝ) / 20) (1+((i : ℝ) + 1) / 20) →
      Obar x = (ci - (cj-ci) * 20*(1+(i : ℝ) / 20)) + ((cj-ci) * 20)*x := by
    filter_upwards [compl_mem_ae_iff.2 (measure_singleton (1 + ((i : ℝ) + 1) / 20))] with x hx hmem
    rw [Set.uIoc_of_le hLR] at hmem
    have hxR : x < 1 + ((i : ℝ) + 1) / 20 := lt_of_le_of_ne hmem.2 (by simpa using hx)
    rw [Obar_panel_eq i hi x ⟨hmem.1.le, hxR⟩]; ring
  rw [intervalIntegral.integral_congr_ae hcong, integral_line]
  field_simp; ring

/-- **Cumulative PL integral** over `[1, 1 + n/20]` = trapezoid partial sum. -/
theorem Obar_cumint (n : ℕ) (hn : n ≤ 220) :
    (∫ v in (1 : ℝ)..(1 + (n : ℝ) / 20), Obar v)
      = ∑ i ∈ Finset.range n, ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40 := by
  induction n with
  | zero => simp
  | succ m ih =>
    have hm : m ≤ 220 := by omega
    have hmlt : m < 220 := by omega
    have hcast : ((m : ℝ) + 1) = ((m+1 : ℕ) : ℝ) := by push_cast; ring
    rw [Finset.sum_range_succ, ← ih hm, ← Obar_panel_integral m hmlt,
        intervalIntegral.integral_add_adjacent_intervals
          (Obar_intervalIntegrable 1 (1 + (m : ℝ) / 20))
          (Obar_intervalIntegrable (1 + (m : ℝ) / 20) (1 + ((m : ℝ) + 1) / 20)), hcast]

theorem Obar_sum_eq_220 :
    ∑ i ∈ Finset.range 220, ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40
      = 11289141/16000000 := by
  have hnat : (∑ i ∈ Finset.range 220, (ObarNum i + ObarNum (i+1))) = 282228525 := by
    simp only [Finset.sum_range_succ, Finset.sum_range_zero, ObarNum, obarNumList,
      List.getD_cons_zero, List.getD_cons_succ]
  have hstep : ∀ i ∈ Finset.range 220,
      ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40
        = ((ObarNum i : ℝ) + (ObarNum (i+1) : ℝ)) / 400000000 := by
    intro i _; unfold ObarKnots; push_cast; ring
  rw [Finset.sum_congr rfl hstep, ← Finset.sum_div,
      show (∑ i ∈ Finset.range 220, ((ObarNum i : ℝ)+(ObarNum (i+1) : ℝ)))
        = ((∑ i ∈ Finset.range 220, (ObarNum i + ObarNum (i+1)) : ℕ) : ℝ) by push_cast; ring,
      hnat]
  norm_num

theorem Obar_sum_eq_40 :
    ∑ i ∈ Finset.range 40, ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40
      = 61872301/100000000 := by
  have hnat : (∑ i ∈ Finset.range 40, (ObarNum i + ObarNum (i+1))) = 247489204 := by
    simp only [Finset.sum_range_succ, Finset.sum_range_zero, ObarNum, obarNumList,
      List.getD_cons_zero, List.getD_cons_succ]
  have hstep : ∀ i ∈ Finset.range 40,
      ((ObarKnots i : ℝ) + (ObarKnots (i+1) : ℝ)) / 40
        = ((ObarNum i : ℝ) + (ObarNum (i+1) : ℝ)) / 400000000 := by
    intro i _; unfold ObarKnots; push_cast; ring
  rw [Finset.sum_congr rfl hstep, ← Finset.sum_div,
      show (∑ i ∈ Finset.range 40, ((ObarNum i : ℝ)+(ObarNum (i+1) : ℝ)))
        = ((∑ i ∈ Finset.range 40, (ObarNum i + ObarNum (i+1)) : ℕ) : ℝ) by push_cast; ring,
      hnat]
  norm_num

/-- `∫_3^12 Obar = 34739321/400000000` (the odd budget's head; the `[1,3)` flat is excluded). -/
theorem Obar_int_3_12 : (∫ w in (3 : ℝ)..12, Obar w) = 34739321/400000000 := by
  have h12 := Obar_cumint 220 (le_refl 220)
  have h3 := Obar_cumint 40 (by norm_num)
  rw [Obar_sum_eq_220] at h12
  rw [Obar_sum_eq_40] at h3
  have e12 : (1 : ℝ) + ((220 : ℕ) : ℝ) / 20 = 12 := by norm_num
  have e3 : (1 : ℝ) + ((40 : ℕ) : ℝ) / 20 = 3 := by norm_num
  rw [e12] at h12
  rw [e3] at h3
  have hadd : (∫ w in (1 : ℝ)..12, Obar w)
      = (∫ w in (1 : ℝ)..3, Obar w) + ∫ w in (3 : ℝ)..12, Obar w :=
    (intervalIntegral.integral_add_adjacent_intervals
      (Obar_intervalIntegrable 1 3) (Obar_intervalIntegrable 3 12)).symm
  linarith [h12, h3, hadd]

/-- **Odd budget.**  `∫_3^b Obar ≤ 11/125` for every `b ≥ 3` (the `hObound` SS1 consumes). -/
theorem Obar_integral_le : ∀ b, 3 ≤ b → (∫ w in (3 : ℝ)..b, Obar w) ≤ 11/125 := by
  intro b hb
  have hle : (34739321/400000000 : ℝ) ≤ 11/125 := by norm_num
  rcases le_or_gt b 12 with hb12 | hb12
  · have hsplit : (∫ w in (3 : ℝ)..12, Obar w)
        = (∫ w in (3 : ℝ)..b, Obar w) + ∫ w in b..12, Obar w :=
      (intervalIntegral.integral_add_adjacent_intervals
        (Obar_intervalIntegrable 3 b) (Obar_intervalIntegrable b 12)).symm
    have htail0 : 0 ≤ ∫ w in b..12, Obar w :=
      intervalIntegral.integral_nonneg hb12 (fun x _ => Obar_nonneg x)
    have h312 := Obar_int_3_12
    linarith
  · have hsplit : (∫ w in (3 : ℝ)..b, Obar w)
        = (∫ w in (3 : ℝ)..12, Obar w) + ∫ w in (12 : ℝ)..b, Obar w :=
      (intervalIntegral.integral_add_adjacent_intervals
        (Obar_intervalIntegrable 3 12) (Obar_intervalIntegrable 12 b)).symm
    have htaileq : (∫ w in (12 : ℝ)..b, Obar w) = ∫ w in (12 : ℝ)..b, (1/10000)/w^3 := by
      apply intervalIntegral.integral_congr
      intro x hx; rw [Set.uIcc_of_le hb12.le] at hx; exact Obar_tail_eq x hx.1
    have htailbd : (∫ w in (12 : ℝ)..b, (1/10000 : ℝ)/w^3) ≤ (1/10000)/(2*12^2) :=
      tail_integral_le (by norm_num) (by norm_num) hb12.le
    have h312 := Obar_int_3_12
    have hbudget : (34739321/400000000 : ℝ) + (1/10000)/(2*12^2) ≤ 11/125 := by norm_num
    linarith

/-! ## Sanity spot checks (regenerated from `scripts/ss2_profile.py`) -/

example : EbarKnots 0 = 10007043 / 10000000 := by norm_num [EbarKnots, EbarNum, ebarNumList]
example : EbarKnots 3 = 1922553 / 2500000 := by norm_num [EbarKnots, EbarNum, ebarNumList]
example : EbarKnots 50 = 31969 / 5000000 := by norm_num [EbarKnots, EbarNum, ebarNumList]
example : EbarKnots 199 = 1 / 10000000 := by norm_num [EbarKnots, EbarNum, ebarNumList]
example : EbarKnots 200 = 1 / 10000000 := by norm_num [EbarKnots, EbarNum, ebarNumList]
example : ObarKnots 0 = 563091 / 1000000 := by norm_num [ObarKnots, ObarNum, obarNumList]
example : ObarKnots 40 = 187697 / 1000000 := by norm_num [ObarKnots, ObarNum, obarNumList]
example : ObarKnots 110 = 3 / 125000 := by norm_num [ObarKnots, ObarNum, obarNumList]
example : ObarKnots 219 = 1 / 10000000 := by norm_num [ObarKnots, ObarNum, obarNumList]
example : ObarKnots 220 = 1 / 10000000 := by norm_num [ObarKnots, ObarNum, obarNumList]

end Salt.Chen
