#!/usr/bin/env python3
"""authorship_extract.py — the authorship-split extractor (PRE-FREEZE, born 2026-08-14).

Three parts, per the prep docket's owed-extractor shape (nature-prep-0814.md §3b):

  (a) TRACKED CENSUS   git ls-files '*.lean' + wc -l per file (newline count,
                       wc semantics), totals per repo.
  (b) MARKER CENSUS    the marker union over the three observed strings —
                       "Generated by" / "MACHINE-GENERATED" / "machine-generated"
                       — full-file scan (NOT a 400-byte head check: CbarCert's
                       marker sits at byte 1204, so the .v classifier's one-command
                       head check returns a FALSE CLEAN on .lean; docket §3b).
                       Per file: total lines, every marker line, and two scope
                       readings (marker-line→EOF, and whole-file).
  (c) GENERATOR JOIN   generator scripts (scripts/, tools/, docs/ledger-tools/)
                       matched to tracked .lean outputs by basename mention, with
                       emits-banner evidence (the generator itself contains a
                       marker string it writes).

This script emits FACTS ONLY. It does not decide the generated/authored
criterion: whether a values-only file (e.g. SuperProfileDef.lean) counts as
generated, and which scope reading a marker gets, are council-ratified rulings
reserved to the Captain at freeze. Aggregates printed here are labeled
CANDIDATES. Marker counts are a LOWER BOUND on script-emitted lines — markers
are voluntary; absence of a marker proves nothing.

Usage: python3 authorship_extract.py <repo_root> [<repo_root> ...]
Read-only: runs `git rev-parse HEAD` and `git ls-files` (queries only), reads
files. Touches no git state.
"""
import os
import subprocess
import sys

MARKERS = ["Generated by", "MACHINE-GENERATED", "machine-generated"]
HEADER_WINDOW = 50   # a marker at/above this line is flagged "header-banner"
GENERATOR_DIRS = ["scripts", "tools", os.path.join("docs", "ledger-tools")]
GENERATOR_EXTS = (".py", ".sh")


def sh(args, cwd):
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True,
                          check=True).stdout


def wc_l(path):
    with open(path, "rb") as fh:
        return fh.read().count(b"\n")


def marker_lines(path):
    """[(lineno, marker, line_text_stripped)] for every marker hit in the file."""
    hits = []
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for i, line in enumerate(fh, 1):
            for m in MARKERS:
                if m in line:
                    hits.append((i, m, line.strip()[:120]))
                    break
    return hits


def census(repo):
    repo = os.path.abspath(repo)
    head = sh(["git", "rev-parse", "HEAD"], repo).strip()
    files = [f for f in sh(["git", "ls-files", "*.lean"], repo).splitlines() if f]

    print(f"==== REPO {repo}")
    print(f"HEAD {head}")

    # (a) tracked census
    per_file = {}
    total = 0
    for f in files:
        n = wc_l(os.path.join(repo, f))
        per_file[f] = n
        total += n
    print(f"(a) tracked census: {len(files)} .lean files, {total} lines "
          f"(git ls-files '*.lean'; wc -l semantics)")

    # (b) marker census
    print(f"(b) marker census — union {MARKERS}, full-file scan:")
    marked = []
    for f in files:
        hits = marker_lines(os.path.join(repo, f))
        if not hits:
            continue
        n = per_file[f]
        first = hits[0][0]
        scope_tail = n - first + 1          # marker-line -> EOF reading
        banner = "header-banner" if first <= HEADER_WINDOW else "mid-file"
        marked.append((f, n, first, scope_tail, banner, hits))
        print(f"  {f}: {n} lines, first marker at line {first} ({banner}), "
              f"marker->EOF scope {scope_tail}, whole-file {n}")
        for (ln, m, txt) in hits[:4]:
            print(f"      :{ln} [{m}] {txt}")
        if len(hits) > 4:
            print(f"      ... {len(hits) - 4} more marker lines")
    if not marked:
        print("  (no marker-bearing tracked .lean files)")
    cand_tail = sum(s for (_, _, _, s, _, _) in marked)
    cand_whole = sum(n for (_, n, _, _, _, _) in marked)
    print(f"  AGGREGATE CANDIDATES (criterion unratified): "
          f"marker->EOF sum {cand_tail}; whole-file sum {cand_whole}; "
          f"tracked total {total}")
    if total:
        print(f"  as % of tracked: {100.0 * cand_tail / total:.2f}% "
              f"(marker->EOF) / {100.0 * cand_whole / total:.2f}% (whole-file) "
              f"— LOWER BOUNDS (markers are voluntary)")

    # (c) generator join
    print("(c) generator join — basename mentions of tracked .lean files inside "
          "generator scripts:")
    basenames = {}
    for f in files:
        basenames.setdefault(os.path.basename(f), []).append(f)
    found_any = False
    for d in GENERATOR_DIRS:
        droot = os.path.join(repo, d)
        if not os.path.isdir(droot):
            continue
        for dirpath, dirnames, filenames in os.walk(droot):
            dirnames[:] = [x for x in dirnames
                           if x not in (".git", ".lake", "index", "__pycache__",
                                        ".venv", "site-packages", "node_modules")]
            for g in sorted(filenames):
                if not g.endswith(GENERATOR_EXTS):
                    continue
                if g == os.path.basename(__file__):
                    continue  # the extractor itself mentions markers and files
                gpath = os.path.join(dirpath, g)
                try:
                    with open(gpath, "r", encoding="utf-8",
                              errors="replace") as fh:
                        text = fh.read()
                except OSError:
                    continue
                joins = sorted(b for b in basenames if b in text)
                emits = [m for m in MARKERS if m in text]
                if joins or emits:
                    found_any = True
                    rel = os.path.relpath(gpath, repo)
                    print(f"  {rel}: mentions {joins if joins else 'none'}; "
                          f"emits-banner evidence {emits if emits else 'none'}")
    if not found_any:
        print("  (no generator mentions found)")
    print()
    return head, len(files), total, marked, cand_tail, cand_whole


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: authorship_extract.py <repo_root> [<repo_root> ...]")
    for r in sys.argv[1:]:
        census(r)
