#!/usr/bin/env python3
"""Generator for Salt/Chen/CbarCert.lean — the CBL tight certificate

    cbar = int_{1/8}^{1/3} log(2-3t)/(t(1-t)) dt < 363084/1000000.

Route (all-rational panels via the LogToolkit `panel_le`/`integral_quad`):
per panel [p,q], midpoint c:
  * log(2-3t) <= tangent at c  (log_lin_le_tangent; rational Lc >= log(2-3c) from Taylor)
  * 1/(t(1-t)) = 1/t + 1/(1-t) <= chord(1/t) + chord(1/(1-t))   (two rational secants)
  * product (tangent)*(chord) is a rational quadratic dominating the integrand;
    its exact integral (integral_quad) is a rational upper bound.
Sum of panel bounds < target.

Cross-checked against mpmath quad.  Emits exact Fraction literals only (no floats in cert).

Usage:  python3 scripts/cbar_cert.py N [--target-actual] > Salt/Chen/CbarCert.lean
  N               number of uniform panels on [1/8,1/3]
  --target-actual make cbar_lt assert `<= (exact panel sum)` instead of `< 363084/1000000`
                  (for build-time measurement at sub-critical N).
"""
import sys
from fractions import Fraction as F
from math import factorial
import mpmath as mp
mp.mp.dps = 60

TARGET = F(363084, 1000000)
NTAYLOR = 12   # Taylor terms in log_le_of_taylor (matches the emitted proof)

def taylor_sum(r, n):
    return sum((r ** i) / F(factorial(i)) for i in range(n))

def logU(x, dec, n=NTAYLOR):
    """Minimal rational r (at 10^-dec granularity) with x <= sum_{i<n} r^i/i!  (=> log x <= r).

    This is the EXACT condition `log_le_of_taylor` checks, so the emitted `Lc` is certified."""
    v = mp.log(mp.mpf(x.numerator) / x.denominator)
    s = 10 ** dec
    r = F(int(mp.floor(v * s)) + 1, s)
    while x > taylor_sum(r, n):
        r += F(1, s)
    return r

def panel(p, q, dec=10, ntaylor=NTAYLOR):
    c = (p + q) / 2
    twoc = 2 - 3 * c
    Lc = logU(twoc, dec, ntaylor)
    assert twoc <= taylor_sum(Lc, ntaylor), (float(twoc), "taylor fails")
    a1 = F(-3, 1) / twoc            # tangent slope
    a0 = Lc - a1 * c                # tangent: log(2-3t) <= a0 + a1 t
    A1 = 1 / p + 1 / q; B1 = F(-1, 1) / (p * q)          # 1/t   <= A1 + B1 t
    B2 = 1 / ((1 - p) * (1 - q)); A2 = 1 / (1 - p) - B2 * p  # 1/(1-t) <= A2 + B2 t
    W0 = A1 + A2; W1 = B1 + B2      # 1/(t(1-t)) <= W0 + W1 t
    C0 = a0 * W0; C1 = a0 * W1 + a1 * W0; C2 = a1 * W1      # product quadratic
    val = C0 * (q - p) + C1 * (q ** 2 - p ** 2) / 2 + C2 * (q ** 3 - p ** 3) / 3
    return dict(c=c, twoc=twoc, Lc=Lc, a0=a0, a1=a1, A1=A1, B1=B1, A2=A2, B2=B2,
                W0=W0, W1=W1, C0=C0, C1=C1, C2=C2, val=val)

def fr(x):
    """Lean literal for a Fraction."""
    if x.denominator == 1:
        return f"({x.numerator})"
    return f"({x.numerator}/{x.denominator})"

def knots(N):
    # p_i = 1/8 + (5/24)(i/N) = (3N + 5i)/(24N)
    return [F(1, 8) + F(5, 24) * F(i, N) for i in range(N + 1)]

def emit(N, target_actual=False, dec=10):
    kn = knots(N)
    panels = [panel(kn[i], kn[i + 1], dec) for i in range(N)]
    total = sum((d['val'] for d in panels), F(0))
    assert target_actual or total < TARGET, (float(total), float(TARGET), "sum exceeds target; increase N")
    out = []
    P = out.append
    P("""/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
import Mathlib
import Salt.Chen.SwitchConstant
import Salt.Chen.LogToolkit

/-!
# CBL — the Chen switch-constant tight certificate `cbar < 0.363084`

Blueprint `chen`, node C4a (deferred at landing), unblocked by the TK1 log-majorant toolkit
(`Salt/Chen/LogToolkit.lean`).  The switch constant is

  `cbar = ∫_{1/8}^{1/3} log(2 − 3t) / (t(1 − t)) dt = 0.363083729248…`

certified below as `cbar < 363084/1000000` (gap ≈ 2.7·10⁻⁷).

## Route (all-rational panels via `panel_le`/`integral_quad`)

On each of the %d uniform panels `[p,q] ⊂ (1/8,1/3)` with midpoint `c`:
* `log(2 − 3t) ≤` its tangent at `c` (`log_lin_le_tangent`; rational `Lc ≥ log(2 − 3c)` via the
  toolkit's Taylor route, `log_le_of_taylor`);
* the convex weight `1/(t(1 − t)) = 1/t + 1/(1 − t) ≤` sum of the two chords (secants), each a
  rational `nlinarith`;
* both bounds nonnegative (`2 − 3t ∈ [1, 13/8] ⇒ log ≥ 0`), so the product quadratic dominates
  the integrand and its exact `integral_quad` value is a rational panel bound.

Generated by `scripts/cbar_cert.py` (exact `Fraction` arithmetic, cross-checked vs mpmath quad).
Panels: %d.  True `cbar = 0.36308373`; certified sum ≈ %s.
-/

open intervalIntegral MeasureTheory Set

set_option linter.style.longLine false
set_option linter.style.whitespace false
set_option maxRecDepth 8000

namespace Salt.Chen

/-- Interval-integrability of the `cbar` integrand on `[a,b]` for `0 < a ≤ b < 2/3`. -/
theorem cbar_ii {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) (hb : b < 2 / 3) :
    IntervalIntegrable (fun s => Real.log (2 - 3*s) / (s * (1 - s))) volume a b := by
  apply ContinuousOn.intervalIntegrable
  apply ContinuousOn.div (ContinuousOn.log (by fun_prop) ?_) (by fun_prop) ?_
  · intro s hs; rw [Set.uIcc_of_le hab] at hs
    have : s ≤ b := hs.2
    exact (show (0:ℝ) < 2 - 3*s by linarith).ne'
  · intro s hs; rw [Set.uIcc_of_le hab] at hs
    have h1 : a ≤ s := hs.1
    have h2 : s ≤ b := hs.2
    exact (mul_pos (by linarith) (by linarith) : (0:ℝ) < s * (1 - s)).ne'

/-- **Tangent (upper) envelope for `log(2 − 3t)`.**  For `0 < 2 − 3c`, `0 < 2 − 3s`, and a rational
`Lc ≥ log(2 − 3c)`, `log(2 − 3s) ≤ Lc − 3(s − c)/(2 − 3c)` (tangent to the concave `log(2 − 3·)`). -/
theorem log_lin_le_tangent {c s Lc : ℝ} (hc : 0 < 2 - 3*c) (hs : 0 < 2 - 3*s)
    (hLc : Real.log (2 - 3*c) ≤ Lc) :
    Real.log (2 - 3*s) ≤ Lc - 3*(s - c) / (2 - 3*c) := by
  have hratio : 0 < (2 - 3*s) / (2 - 3*c) := div_pos hs hc
  have h1 : Real.log ((2 - 3*s) / (2 - 3*c)) ≤ (2 - 3*s) / (2 - 3*c) - 1 :=
    Real.log_le_sub_one_of_pos hratio
  have h2 : Real.log (2 - 3*s) - Real.log (2 - 3*c) = Real.log ((2 - 3*s) / (2 - 3*c)) := by
    rw [← Real.log_div hs.ne' hc.ne']
  have h3 : (2 - 3*s) / (2 - 3*c) - 1 = -(3*(s - c) / (2 - 3*c)) := by field_simp; ring
  linarith [h1, h2, hLc, h3]
""" % (N, N, mp.nstr(mp.mpf(total.numerator) / total.denominator, 12)))

    # per-panel log knots + panel bounds
    for i, d in enumerate(panels):
        p, q = kn[i], kn[i + 1]
        c = d['c']
        P(f"/-- Panel {i} log knot: `log(2 − 3·{fr(c)}) ≤ {d['Lc']}`. -/")
        P(f"theorem cbar_lk_{i} : Real.log (2 - 3*({fr(c)} : ℝ)) ≤ {fr(d['Lc'])} :=")
        P(f"  log_le_of_taylor (by norm_num) {NTAYLOR} (by norm_num)")
        P(f"    (by norm_num [Finset.sum_range_succ, Nat.factorial])")
        P("")
        P(f"/-- Panel {i} upper: `∫_{fr(p)}^{fr(q)} log(2−3s)/(s(1−s)) ≤ {d['val']}`. -/")
        P(f"theorem cbar_U_{i} :")
        P(f"    (∫ s in ({fr(p)}:ℝ)..{fr(q)}, Real.log (2 - 3*s) / (s * (1 - s))) ≤ {fr(d['val'])} := by")
        P(f"  apply panel_le _ (A := {fr(d['C0'])}) (B := {fr(d['C1'])}) (C := {fr(d['C2'])})")
        P(f"    (by norm_num) (cbar_ii (by norm_num) (by norm_num) (by norm_num)) ?_ (by norm_num)")
        P(f"  intro s hs; obtain ⟨hsp, hsq⟩ := hs")
        P(f"  have hs0 : (0:ℝ) < s := by linarith")
        P(f"  have hs1 : (0:ℝ) < 1 - s := by linarith")
        P(f"  have h23 : (0:ℝ) < 2 - 3*s := by linarith")
        P(f"  have htan := log_lin_le_tangent (c := ({fr(c)} : ℝ)) (s := s) (by norm_num) h23 cbar_lk_{i}")
        P(f"  have heq : ({fr(d['Lc'])} : ℝ) - 3*(s - {fr(c)}) / (2 - 3*{fr(c)}) = {fr(d['a0'])} + {fr(d['a1'])} * s := by")
        P(f"    field_simp; ring")
        P(f"  have hlog : Real.log (2 - 3*s) ≤ {fr(d['a0'])} + {fr(d['a1'])} * s := heq ▸ htan")
        P(f"  have hlognn : 0 ≤ Real.log (2 - 3*s) := Real.log_nonneg (by linarith)")
        P(f"  have hTnn : 0 ≤ ({fr(d['a0'])} : ℝ) + {fr(d['a1'])} * s := le_trans hlognn hlog")
        P(f"  have hW1 : 1/s ≤ ({fr(d['A1'])}:ℝ) + {fr(d['B1'])} * s := by")
        P(f"    rw [div_le_iff₀ hs0]; nlinarith [mul_nonneg (sub_nonneg.2 hsp) (sub_nonneg.2 hsq)]")
        P(f"  have hW2 : 1/(1-s) ≤ ({fr(d['A2'])}:ℝ) + {fr(d['B2'])} * s := by")
        P(f"    rw [div_le_iff₀ hs1]; nlinarith [mul_nonneg (sub_nonneg.2 hsp) (sub_nonneg.2 hsq)]")
        P(f"  have hWid : 1/(s*(1-s)) = 1/s + 1/(1-s) := by field_simp; ring")
        P(f"  have hW : 1/(s*(1-s)) ≤ ({fr(d['W0'])}:ℝ) + {fr(d['W1'])} * s := by rw [hWid]; linarith [hW1, hW2]")
        P(f"  have hWnn : 0 ≤ 1/(s*(1-s)) := by positivity")
        P(f"  calc Real.log (2 - 3*s) / (s * (1 - s)) = Real.log (2 - 3*s) * (1/(s*(1-s))) := by rw [mul_one_div]")
        P(f"    _ ≤ ({fr(d['a0'])} + {fr(d['a1'])} * s) * ({fr(d['W0'])} + {fr(d['W1'])} * s) :=")
        P(f"        mul_le_mul hlog hW hWnn hTnn")
        P(f"    _ = {fr(d['C0'])} + {fr(d['C1'])} * s + {fr(d['C2'])} * s ^ 2 := by ring")
        P("")

    # assembly: TWO-LEVEL block decomposition (single-level telescoping grows the goal to N terms,
    # so late rewrites are O(N) each and blow the heartbeat wall at large N).  Each block of `BLK`
    # panels is telescoped locally (small goal) into a rounded rational block bound; then the B
    # block bounds are telescoped/summed against the target.
    BLK = 25
    bstarts = list(range(0, N, BLK))
    # block bound = ceil(block panel-sum * 10^12)/10^12 (small literal; rounding cost <= B*1e-12)
    def blk_bound(bi):
        lo = bstarts[bi]; hi = min(lo + BLK, N)
        s = sum((panels[j]['val'] for j in range(lo, hi)), F(0))
        num = -(-(s.numerator * (10 ** 12)) // s.denominator)   # ceil(s * 1e12)
        return F(num, 10 ** 12), lo, hi
    blkdata = [blk_bound(bi) for bi in range(len(bstarts))]
    blocktotal = sum((bb for bb, _, _ in blkdata), F(0))
    assert target_actual or blocktotal < TARGET, (float(blocktotal), float(TARGET), "block-rounded sum exceeds target")

    for bi, (bb, lo, hi) in enumerate(blkdata):
        p0, pN = fr(kn[lo]), fr(kn[hi])
        P(f"/-- Block {bi}: `∫_{p0}^{pN} log(2−3s)/(s(1−s)) ≤ {bb}` (panels {lo}..{hi - 1}). -/")
        P(f"theorem cbar_blk_{bi} :")
        P(f"    (∫ s in ({p0}:ℝ)..{pN}, Real.log (2 - 3*s) / (s * (1 - s))) ≤ {fr(bb)} := by")
        for j in range(lo, hi - 1):
            aj, ajp1 = fr(kn[j]), fr(kn[j + 1])
            P(f"  rw [← intervalIntegral.integral_add_adjacent_intervals")
            P(f"    (cbar_ii (a := {aj}) (b := {ajp1}) (by norm_num) (by norm_num) (by norm_num))")
            P(f"    (cbar_ii (a := {ajp1}) (b := {pN}) (by norm_num) (by norm_num) (by norm_num))]")
        P("  linarith [" + ", ".join(f"cbar_U_{j}" for j in range(lo, hi)) + "]")
        P("")

    P("/-- **CBL — the tight switch-constant certificate.**  `cbar < 363084/1000000`. -/")
    if target_actual:
        P(f"theorem cbar_lt : cbar ≤ {fr(blocktotal)} := by")
    else:
        # emit the target verbatim as 363084/1000000 (the deferred-slot literal), not reduced
        P(f"theorem cbar_lt : cbar < 363084/1000000 := by")
    P("  unfold cbar")
    for bi in range(len(bstarts) - 1):
        lo = bstarts[bi]; hi = min(lo + BLK, N)
        bs, be, bend = fr(kn[lo]), fr(kn[hi]), fr(kn[N])
        P(f"  rw [← intervalIntegral.integral_add_adjacent_intervals")
        P(f"    (cbar_ii (a := {bs}) (b := {be}) (by norm_num) (by norm_num) (by norm_num))")
        P(f"    (cbar_ii (a := {be}) (b := {bend}) (by norm_num) (by norm_num) (by norm_num))]")
    P("  linarith [" + ", ".join(f"cbar_blk_{bi}" for bi in range(len(bstarts))) + "]")
    P("")
    P("end Salt.Chen")
    return "\n".join(out), float(total)

if __name__ == "__main__":
    N = int(sys.argv[1])
    ta = "--target-actual" in sys.argv
    text, total = emit(N, target_actual=ta)
    sys.stderr.write(f"N={N} sum={total:.10f} target={float(TARGET):.10f} margin={float(TARGET)-total:.3e} {'(sub-critical)' if total>=float(TARGET) else 'OK'}\n")
    sys.stdout.write(text)
